{1},{2},len({1}),len({2})
Autauga County,Alabama,14,7
Baldwin County,Alabama,14,7
Barbour County,Alabama,14,7
Bibb County,Alabama,11,7
Blount County,Alabama,13,7
Bullock County,Alabama,14,7
Butler County,Alabama,13,7
Calhoun County,Alabama,14,7
Chambers County,Alabama,15,7
Cherokee County,Alabama,15,7
Chilton County,Alabama,14,7
Choctaw County,Alabama,14,7
Clarke County,Alabama,13,7
Clay County,Alabama,11,7
Cleburne County,Alabama,15,7
Coffee County,Alabama,13,7
Colbert County,Alabama,14,7
Conecuh County,Alabama,14,7
Coosa County,Alabama,12,7
Covington County,Alabama,16,7
Crenshaw County,Alabama,15,7
Cullman County,Alabama,14,7
Dale County,Alabama,11,7
Dallas County,Alabama,13,7
DeKalb County,Alabama,13,7
Elmore County,Alabama,13,7
Escambia County,Alabama,15,7
Etowah County,Alabama,13,7
Fayette County,Alabama,14,7
Franklin County,Alabama,15,7
Geneva County,Alabama,13,7
Greene County,Alabama,13,7
Hale County,Alabama,11,7
Henry County,Alabama,12,7
Houston County,Alabama,14,7
Jackson County,Alabama,14,7
Jefferson County,Alabama,16,7
Lamar County,Alabama,12,7
Lauderdale County,Alabama,17,7
Lawrence County,Alabama,15,7
Lee County,Alabama,10,7
Limestone County,Alabama,16,7
Lowndes County,Alabama,14,7
Macon County,Alabama,12,7
Madison County,Alabama,14,7
Marengo County,Alabama,14,7
Marion County,Alabama,13,7
Marshall County,Alabama,15,7
Mobile County,Alabama,13,7
Monroe County,Alabama,13,7
Montgomery County,Alabama,17,7
Morgan County,Alabama,13,7
Perry County,Alabama,12,7
Pickens County,Alabama,14,7
Pike County,Alabama,11,7
Randolph County,Alabama,15,7
Russell County,Alabama,14,7
Shelby County,Alabama,13,7
St. Clair County,Alabama,16,7
Sumter County,Alabama,13,7
Talladega County,Alabama,16,7
Tallapoosa County,Alabama,17,7
Tuscaloosa County,Alabama,17,7
Walker County,Alabama,13,7
Washington County,Alabama,17,7
Wilcox County,Alabama,13,7
Winston County,Alabama,14,7
Aleutians East Borough,Alaska,22,6
Aleutians West Census Area,Alaska,26,6
Bethel Census Area,Alaska,18,6
Bristol Bay Borough,Alaska,19,6
Denali Borough,Alaska,14,6
Dillingham Census Area,Alaska,22,6
Fairbanks North Star Borough,Alaska,28,6
Haines Borough,Alaska,14,6
Juneau City and Borough,Alaska,23,6
Kenai Peninsula Borough,Alaska,23,6
Ketchikan Gateway Borough,Alaska,25,6
Kodiak Island Borough,Alaska,21,6
Lake and Peninsula Borough,Alaska,26,6
Matanuska-Susitna Borough,Alaska,25,6
Nome Census Area,Alaska,16,6
North Slope Borough,Alaska,19,6
Northwest Arctic Borough,Alaska,24,6
Prince of Wales-Outer Ketchikan Census Area,Alaska,43,6
Sitka City and Borough,Alaska,22,6
Skagway-Hoonah-Angoon Census Area,Alaska,33,6
Southeast Fairbanks Census Area,Alaska,31,6
Valdez-Cordova Census Area,Alaska,26,6
Wade Hampton Census Area,Alaska,24,6
Wrangell-Petersburg Census Area,Alaska,31,6
Yakutat City and Borough,Alaska,24,6
Yukon-Koyukuk Census Area,Alaska,25,6
Municipality of Anchorage,Alaska,25,6
Apache County,Arizona,13,7
Cochise County,Arizona,14,7
Coconino County,Arizona,15,7
Gila County,Arizona,11,7
Graham County,Arizona,13,7
Greenlee County,Arizona,15,7
La Paz County,Arizona,13,7
Maricopa County,Arizona,15,7
Mohave County,Arizona,13,7
Navajo County,Arizona,13,7
Pima County,Arizona,11,7
Pinal County,Arizona,12,7
Santa Cruz County,Arizona,17,7
Yavapai County,Arizona,14,7
Yuma County,Arizona,11,7
Arkansas County,Arkansas,15,8
Ashley County,Arkansas,13,8
Baxter County,Arkansas,13,8
Benton County,Arkansas,13,8
Boone County,Arkansas,12,8
Bradley County,Arkansas,14,8
Calhoun County,Arkansas,14,8
Carroll County,Arkansas,14,8
Chicot County,Arkansas,13,8
Clark County,Arkansas,12,8
Clay County,Arkansas,11,8
Cleburne County,Arkansas,15,8
Cleveland County,Arkansas,16,8
Columbia County,Arkansas,15,8
Conway County,Arkansas,13,8
Craighead County,Arkansas,16,8
Crawford County,Arkansas,15,8
Crittenden County,Arkansas,17,8
Cross County,Arkansas,12,8
Dallas County,Arkansas,13,8
Desha County,Arkansas,12,8
Drew County,Arkansas,11,8
Faulkner County,Arkansas,15,8
Franklin County,Arkansas,15,8
Fulton County,Arkansas,13,8
Garland County,Arkansas,14,8
Grant County,Arkansas,12,8
Greene County,Arkansas,13,8
Hempstead County,Arkansas,16,8
Hot Spring County,Arkansas,17,8
Howard County,Arkansas,13,8
Independence County,Arkansas,19,8
Izard County,Arkansas,12,8
Jackson County,Arkansas,14,8
Jefferson County,Arkansas,16,8
Johnson County,Arkansas,14,8
Lafayette County,Arkansas,16,8
Lawrence County,Arkansas,15,8
Lee County,Arkansas,10,8
Lincoln County,Arkansas,14,8
Little River County,Arkansas,19,8
Logan County,Arkansas,12,8
Lonoke County,Arkansas,13,8
Madison County,Arkansas,14,8
Marion County,Arkansas,13,8
Miller County,Arkansas,13,8
Mississippi County,Arkansas,18,8
Monroe County,Arkansas,13,8
Montgomery County,Arkansas,17,8
Nevada County,Arkansas,13,8
Newton County,Arkansas,13,8
Ouachita County,Arkansas,15,8
Perry County,Arkansas,12,8
Phillips County,Arkansas,15,8
Pike County,Arkansas,11,8
Poinsett County,Arkansas,15,8
Polk County,Arkansas,11,8
Pope County,Arkansas,11,8
Prairie County,Arkansas,14,8
Pulaski County,Arkansas,14,8
Randolph County,Arkansas,15,8
Saline County,Arkansas,13,8
Scott County,Arkansas,12,8
Searcy County,Arkansas,13,8
Sebastian County,Arkansas,16,8
Sevier County,Arkansas,13,8
Sharp County,Arkansas,12,8
St. Francis County,Arkansas,18,8
Stone County,Arkansas,12,8
Union County,Arkansas,12,8
Van Buren County,Arkansas,16,8
Washington County,Arkansas,17,8
White County,Arkansas,12,8
Woodruff County,Arkansas,15,8
Yell County,Arkansas,11,8
Alameda County,California,14,10
Alpine County,California,13,10
Amador County,California,13,10
Butte County,California,12,10
Calaveras County,California,16,10
Colusa County,California,13,10
Contra Costa County,California,19,10
Del Norte County,California,16,10
El Dorado County,California,16,10
Fresno County,California,13,10
Glenn County,California,12,10
Humboldt County,California,15,10
Imperial County,California,15,10
Inyo County,California,11,10
Kern County,California,11,10
Kings County,California,12,10
Lake County,California,11,10
Lassen County,California,13,10
Los Angeles County,California,18,10
Madera County,California,13,10
Marin County,California,12,10
Mariposa County,California,15,10
Mendocino County,California,16,10
Merced County,California,13,10
Modoc County,California,12,10
Mono County,California,11,10
Monterey County,California,15,10
Napa County,California,11,10
Nevada County,California,13,10
Orange County,California,13,10
Placer County,California,13,10
Plumas County,California,13,10
Riverside County,California,16,10
Sacramento County,California,17,10
San Benito County,California,17,10
San Bernardino County,California,21,10
San Diego County,California,16,10
San Francisco,California,13,10
San Joaquin County,California,18,10
San Luis Obispo County,California,22,10
San Mateo County,California,16,10
Santa Barbara County,California,20,10
Santa Clara County,California,18,10
Santa Cruz County,California,17,10
Shasta County,California,13,10
Sierra County,California,13,10
Siskiyou County,California,15,10
Solano County,California,13,10
Sonoma County,California,13,10
Stanislaus County,California,17,10
Sutter County,California,13,10
Tehama County,California,13,10
Trinity County,California,14,10
Tulare County,California,13,10
Tuolumne County,California,15,10
Ventura County,California,14,10
Yolo County,California,11,10
Yuba County,California,11,10
Adams County,Colorado,12,8
Alamosa County,Colorado,14,8
Arapahoe County,Colorado,15,8
Archuleta County,Colorado,16,8
Baca County,Colorado,11,8
Bent County,Colorado,11,8
Boulder County,Colorado,14,8
Broomfield County,Colorado,17,8
Chaffee County,Colorado,14,8
Cheyenne County,Colorado,15,8
Clear Creek County,Colorado,18,8
Conejos County,Colorado,14,8
Costilla County,Colorado,15,8
Crowley County,Colorado,14,8
Custer County,Colorado,13,8
Delta County,Colorado,12,8
Denver County,Colorado,13,8
Dolores County,Colorado,14,8
Douglas County,Colorado,14,8
Eagle County,Colorado,12,8
El Paso County,Colorado,14,8
Elbert County,Colorado,13,8
Fremont County,Colorado,14,8
Garfield County,Colorado,15,8
Gilpin County,Colorado,13,8
Grand County,Colorado,12,8
Gunnison County,Colorado,15,8
Hinsdale County,Colorado,15,8
Huerfano County,Colorado,15,8
Jackson County,Colorado,14,8
Jefferson County,Colorado,16,8
Kiowa County,Colorado,12,8
Kit Carson County,Colorado,17,8
La Plata County,Colorado,15,8
Lake County,Colorado,11,8
Larimer County,Colorado,14,8
Las Animas County,Colorado,17,8
Lincoln County,Colorado,14,8
Logan County,Colorado,12,8
Mesa County,Colorado,11,8
Mineral County,Colorado,14,8
Moffat County,Colorado,13,8
Montezuma County,Colorado,16,8
Montrose County,Colorado,15,8
Morgan County,Colorado,13,8
Otero County,Colorado,12,8
Ouray County,Colorado,12,8
Park County,Colorado,11,8
Phillips County,Colorado,15,8
Pitkin County,Colorado,13,8
Prowers County,Colorado,14,8
Pueblo County,Colorado,13,8
Rio Blanco County,Colorado,17,8
Rio Grande County,Colorado,17,8
Routt County,Colorado,12,8
Saguache County,Colorado,15,8
San Juan County,Colorado,15,8
San Miguel County,Colorado,17,8
Sedgwick County,Colorado,15,8
Summit County,Colorado,13,8
Teller County,Colorado,13,8
Washington County,Colorado,17,8
Weld County,Colorado,11,8
Yuma County,Colorado,11,8
Fairfield County,Connecticut,16,11
Hartford County,Connecticut,15,11
Litchfield County,Connecticut,17,11
Middlesex County,Connecticut,16,11
New Haven County,Connecticut,16,11
New London County,Connecticut,17,11
Tolland County,Connecticut,14,11
Windham County,Connecticut,14,11
Kent County,Delaware,11,8
New Castle County,Delaware,17,8
Sussex County,Delaware,13,8
District of Columbia County,District of Columbia,27,20
Alachua County,Florida,14,7
Baker County,Florida,12,7
Bay County,Florida,10,7
Bradford County,Florida,15,7
Brevard County,Florida,14,7
Broward County,Florida,14,7
Calhoun County,Florida,14,7
Charlotte County,Florida,16,7
Citrus County,Florida,13,7
Clay County,Florida,11,7
Collier County,Florida,14,7
Columbia County,Florida,15,7
DeSoto County,Florida,13,7
Dixie County,Florida,12,7
Duval County,Florida,12,7
Escambia County,Florida,15,7
Flagler County,Florida,14,7
Franklin County,Florida,15,7
Gadsden County,Florida,14,7
Gilchrist County,Florida,16,7
Glades County,Florida,13,7
Gulf County,Florida,11,7
Hamilton County,Florida,15,7
Hardee County,Florida,13,7
Hendry County,Florida,13,7
Hernando County,Florida,15,7
Highlands County,Florida,16,7
Hillsborough County,Florida,19,7
Holmes County,Florida,13,7
Indian River County,Florida,19,7
Jackson County,Florida,14,7
Jefferson County,Florida,16,7
Lafayette County,Florida,16,7
Lake County,Florida,11,7
Lee County,Florida,10,7
Leon County,Florida,11,7
Levy County,Florida,11,7
Liberty County,Florida,14,7
Madison County,Florida,14,7
Manatee County,Florida,14,7
Marion County,Florida,13,7
Martin County,Florida,13,7
Miami-Dade County,Florida,17,7
Monroe County,Florida,13,7
Nassau County,Florida,13,7
Okaloosa County,Florida,15,7
Okeechobee County,Florida,17,7
Orange County,Florida,13,7
Osceola County,Florida,14,7
Palm Beach County,Florida,17,7
Pasco County,Florida,12,7
Pinellas County,Florida,15,7
Polk County,Florida,11,7
Putnam County,Florida,13,7
Santa Rosa County,Florida,17,7
Sarasota County,Florida,15,7
Seminole County,Florida,15,7
St. Johns County,Florida,16,7
St. Lucie County,Florida,16,7
Sumter County,Florida,13,7
Suwannee County,Florida,15,7
Taylor County,Florida,13,7
Union County,Florida,12,7
Volusia County,Florida,14,7
Wakulla County,Florida,14,7
Walton County,Florida,13,7
Washington County,Florida,17,7
Appling County,Georgia,14,7
Atkinson County,Georgia,15,7
Bacon County,Georgia,12,7
Baker County,Georgia,12,7
Baldwin County,Georgia,14,7
Banks County,Georgia,12,7
Barrow County,Georgia,13,7
Bartow County,Georgia,13,7
Ben Hill County,Georgia,15,7
Berrien County,Georgia,14,7
Bibb County,Georgia,11,7
Bleckley County,Georgia,15,7
Brantley County,Georgia,15,7
Brooks County,Georgia,13,7
Bryan County,Georgia,12,7
Bulloch County,Georgia,14,7
Burke County,Georgia,12,7
Butts County,Georgia,12,7
Calhoun County,Georgia,14,7
Camden County,Georgia,13,7
Candler County,Georgia,14,7
Carroll County,Georgia,14,7
Catoosa County,Georgia,14,7
Charlton County,Georgia,15,7
Chatham County,Georgia,14,7
Chattahoochee County,Georgia,20,7
Chattooga County,Georgia,16,7
Cherokee County,Georgia,15,7
Clarke County,Georgia,13,7
Clay County,Georgia,11,7
Clayton County,Georgia,14,7
Clinch County,Georgia,13,7
Cobb County,Georgia,11,7
Coffee County,Georgia,13,7
Colquitt County,Georgia,15,7
Columbia County,Georgia,15,7
Cook County,Georgia,11,7
Coweta County,Georgia,13,7
Crawford County,Georgia,15,7
Crisp County,Georgia,12,7
Dade County,Georgia,11,7
Dawson County,Georgia,13,7
De Kalb County,Georgia,14,7
Decatur County,Georgia,14,7
Dodge County,Georgia,12,7
Dooly County,Georgia,12,7
Dougherty County,Georgia,16,7
Douglas County,Georgia,14,7
Early County,Georgia,12,7
Echols County,Georgia,13,7
Effingham County,Georgia,16,7
Elbert County,Georgia,13,7
Emanuel County,Georgia,14,7
Evans County,Georgia,12,7
Fannin County,Georgia,13,7
Fayette County,Georgia,14,7
Floyd County,Georgia,12,7
Forsyth County,Georgia,14,7
Franklin County,Georgia,15,7
Fulton County,Georgia,13,7
Gilmer County,Georgia,13,7
Glascock County,Georgia,15,7
Glynn County,Georgia,12,7
Gordon County,Georgia,13,7
Grady County,Georgia,12,7
Greene County,Georgia,13,7
Gwinnett County,Georgia,15,7
Habersham County,Georgia,16,7
Hall County,Georgia,11,7
Hancock County,Georgia,14,7
Haralson County,Georgia,15,7
Harris County,Georgia,13,7
Hart County,Georgia,11,7
Heard County,Georgia,12,7
Henry County,Georgia,12,7
Houston County,Georgia,14,7
Irwin County,Georgia,12,7
Jackson County,Georgia,14,7
Jasper County,Georgia,13,7
Jeff Davis County,Georgia,17,7
Jefferson County,Georgia,16,7
Jenkins County,Georgia,14,7
Johnson County,Georgia,14,7
Jones County,Georgia,12,7
Lamar County,Georgia,12,7
Lanier County,Georgia,13,7
Laurens County,Georgia,14,7
Lee County,Georgia,10,7
Liberty County,Georgia,14,7
Lincoln County,Georgia,14,7
Long County,Georgia,11,7
Lowndes County,Georgia,14,7
Lumpkin County,Georgia,14,7
Macon County,Georgia,12,7
Madison County,Georgia,14,7
Marion County,Georgia,13,7
McDuffie County,Georgia,15,7
McIntosh County,Georgia,15,7
Meriwether County,Georgia,17,7
Miller County,Georgia,13,7
Mitchell County,Georgia,15,7
Monroe County,Georgia,13,7
Montgomery County,Georgia,17,7
Morgan County,Georgia,13,7
Murray County,Georgia,13,7
Muscogee County,Georgia,15,7
Newton County,Georgia,13,7
Oconee County,Georgia,13,7
Oglethorpe County,Georgia,17,7
Paulding County,Georgia,15,7
Peach County,Georgia,12,7
Pickens County,Georgia,14,7
Pierce County,Georgia,13,7
Pike County,Georgia,11,7
Polk County,Georgia,11,7
Pulaski County,Georgia,14,7
Putnam County,Georgia,13,7
Quitman County,Georgia,14,7
Rabun County,Georgia,12,7
Randolph County,Georgia,15,7
Richmond County,Georgia,15,7
Rockdale County,Georgia,15,7
Schley County,Georgia,13,7
Screven County,Georgia,14,7
Seminole County,Georgia,15,7
Spalding County,Georgia,15,7
Stephens County,Georgia,15,7
Stewart County,Georgia,14,7
Sumter County,Georgia,13,7
Talbot County,Georgia,13,7
Taliaferro County,Georgia,17,7
Tattnall County,Georgia,15,7
Taylor County,Georgia,13,7
Telfair County,Georgia,14,7
Terrell County,Georgia,14,7
Thomas County,Georgia,13,7
Tift County,Georgia,11,7
Toombs County,Georgia,13,7
Towns County,Georgia,12,7
Treutlen County,Georgia,15,7
Troup County,Georgia,12,7
Turner County,Georgia,13,7
Twiggs County,Georgia,13,7
Union County,Georgia,12,7
Upson County,Georgia,12,7
Walker County,Georgia,13,7
Walton County,Georgia,13,7
Ware County,Georgia,11,7
Warren County,Georgia,13,7
Washington County,Georgia,17,7
Wayne County,Georgia,12,7
Webster County,Georgia,14,7
Wheeler County,Georgia,14,7
White County,Georgia,12,7
Whitfield County,Georgia,16,7
Wilcox County,Georgia,13,7
Wilkes County,Georgia,13,7
Wilkinson County,Georgia,16,7
Worth County,Georgia,12,7
Hawaii County,Hawaii,13,6
Honolulu County,Hawaii,15,6
Kalawao County,Hawaii,14,6
Kauai County,Hawaii,12,6
Maui County,Hawaii,11,6
Ada County,Idaho,10,5
Adams County,Idaho,12,5
Bannock County,Idaho,14,5
Bear Lake County,Idaho,16,5
Benewah County,Idaho,14,5
Bingham County,Idaho,14,5
Blaine County,Idaho,13,5
Boise County,Idaho,12,5
Bonner County,Idaho,13,5
Bonneville County,Idaho,17,5
Boundary County,Idaho,15,5
Butte County,Idaho,12,5
Camas County,Idaho,12,5
Canyon County,Idaho,13,5
Caribou County,Idaho,14,5
Cassia County,Idaho,13,5
Clark County,Idaho,12,5
Clearwater County,Idaho,17,5
Custer County,Idaho,13,5
Elmore County,Idaho,13,5
Franklin County,Idaho,15,5
Fremont County,Idaho,14,5
Gem County,Idaho,10,5
Gooding County,Idaho,14,5
Idaho County,Idaho,12,5
Jefferson County,Idaho,16,5
Jerome County,Idaho,13,5
Kootenai County,Idaho,15,5
Latah County,Idaho,12,5
Lemhi County,Idaho,12,5
Lewis County,Idaho,12,5
Lincoln County,Idaho,14,5
Madison County,Idaho,14,5
Minidoka County,Idaho,15,5
Nez Perce County,Idaho,16,5
Oneida County,Idaho,13,5
Owyhee County,Idaho,13,5
Payette County,Idaho,14,5
Power County,Idaho,12,5
Shoshone County,Idaho,15,5
Teton County,Idaho,12,5
Twin Falls County,Idaho,17,5
Valley County,Idaho,13,5
Washington County,Idaho,17,5
Adams County,Illinois,12,8
Alexander County,Illinois,16,8
Bond County,Illinois,11,8
Boone County,Illinois,12,8
Brown County,Illinois,12,8
Bureau County,Illinois,13,8
Calhoun County,Illinois,14,8
Carroll County,Illinois,14,8
Cass County,Illinois,11,8
Champaign County,Illinois,16,8
Christian County,Illinois,16,8
Clark County,Illinois,12,8
Clay County,Illinois,11,8
Clinton County,Illinois,14,8
Coles County,Illinois,12,8
Cook County,Illinois,11,8
Crawford County,Illinois,15,8
Cumberland County,Illinois,17,8
DeKalb County,Illinois,13,8
De Witt County,Illinois,14,8
Douglas County,Illinois,14,8
Du Page County,Illinois,14,8
Edgar County,Illinois,12,8
Edwards County,Illinois,14,8
Effingham County,Illinois,16,8
Fayette County,Illinois,14,8
Ford County,Illinois,11,8
Franklin County,Illinois,15,8
Fulton County,Illinois,13,8
Gallatin County,Illinois,15,8
Greene County,Illinois,13,8
Grundy County,Illinois,13,8
Hamilton County,Illinois,15,8
Hancock County,Illinois,14,8
Hardin County,Illinois,13,8
Henderson County,Illinois,16,8
Henry County,Illinois,12,8
Iroquois County,Illinois,15,8
Jackson County,Illinois,14,8
Jasper County,Illinois,13,8
Jefferson County,Illinois,16,8
Jersey County,Illinois,13,8
Jo Daviess County,Illinois,17,8
Johnson County,Illinois,14,8
Kane County,Illinois,11,8
Kankakee County,Illinois,15,8
Kendall County,Illinois,14,8
Knox County,Illinois,11,8
La Salle County,Illinois,15,8
Lake County,Illinois,11,8
Lawrence County,Illinois,15,8
Lee County,Illinois,10,8
Livingston County,Illinois,17,8
Logan County,Illinois,12,8
Macon County,Illinois,12,8
Macoupin County,Illinois,15,8
Madison County,Illinois,14,8
Marion County,Illinois,13,8
Marshall County,Illinois,15,8
Mason County,Illinois,12,8
Massac County,Illinois,13,8
McDonough County,Illinois,16,8
McHenry County,Illinois,14,8
McLean County,Illinois,13,8
Menard County,Illinois,13,8
Mercer County,Illinois,13,8
Monroe County,Illinois,13,8
Montgomery County,Illinois,17,8
Morgan County,Illinois,13,8
Moultrie County,Illinois,15,8
Ogle County,Illinois,11,8
Peoria County,Illinois,13,8
Perry County,Illinois,12,8
Piatt County,Illinois,12,8
Pike County,Illinois,11,8
Pope County,Illinois,11,8
Pulaski County,Illinois,14,8
Putnam County,Illinois,13,8
Randolph County,Illinois,15,8
Richland County,Illinois,15,8
Rock Island County,Illinois,18,8
Saline County,Illinois,13,8
Sangamon County,Illinois,15,8
Schuyler County,Illinois,15,8
Scott County,Illinois,12,8
Shelby County,Illinois,13,8
St. Clair County,Illinois,16,8
Stark County,Illinois,12,8
Stephenson County,Illinois,17,8
Tazewell County,Illinois,15,8
Union County,Illinois,12,8
Vermilion County,Illinois,16,8
Wabash County,Illinois,13,8
Warren County,Illinois,13,8
Washington County,Illinois,17,8
Wayne County,Illinois,12,8
White County,Illinois,12,8
Whiteside County,Illinois,16,8
Will County,Illinois,11,8
Williamson County,Illinois,17,8
Winnebago County,Illinois,16,8
Woodford County,Illinois,15,8
Adams County,Indiana,12,7
Allen County,Indiana,12,7
Bartholomew County,Indiana,18,7
Benton County,Indiana,13,7
Blackford County,Indiana,16,7
Boone County,Indiana,12,7
Brown County,Indiana,12,7
Carroll County,Indiana,14,7
Cass County,Indiana,11,7
Clark County,Indiana,12,7
Clay County,Indiana,11,7
Clinton County,Indiana,14,7
Crawford County,Indiana,15,7
Daviess County,Indiana,14,7
De Kalb County,Indiana,14,7
Dearborn County,Indiana,15,7
Decatur County,Indiana,14,7
Delaware County,Indiana,15,7
Dubois County,Indiana,13,7
Elkhart County,Indiana,14,7
Fayette County,Indiana,14,7
Floyd County,Indiana,12,7
Fountain County,Indiana,15,7
Franklin County,Indiana,15,7
Fulton County,Indiana,13,7
Gibson County,Indiana,13,7
Grant County,Indiana,12,7
Greene County,Indiana,13,7
Hamilton County,Indiana,15,7
Hancock County,Indiana,14,7
Harrison County,Indiana,15,7
Hendricks County,Indiana,16,7
Henry County,Indiana,12,7
Howard County,Indiana,13,7
Huntington County,Indiana,17,7
Jackson County,Indiana,14,7
Jasper County,Indiana,13,7
Jay County,Indiana,10,7
Jefferson County,Indiana,16,7
Jennings County,Indiana,15,7
Johnson County,Indiana,14,7
Knox County,Indiana,11,7
Kosciusko County,Indiana,16,7
La Porte County,Indiana,15,7
Lagrange County,Indiana,15,7
Lake County,Indiana,11,7
Lawrence County,Indiana,15,7
Madison County,Indiana,14,7
Marion County,Indiana,13,7
Marshall County,Indiana,15,7
Martin County,Indiana,13,7
Miami County,Indiana,12,7
Monroe County,Indiana,13,7
Montgomery County,Indiana,17,7
Morgan County,Indiana,13,7
Newton County,Indiana,13,7
Noble County,Indiana,12,7
Ohio County,Indiana,11,7
Orange County,Indiana,13,7
Owen County,Indiana,11,7
Parke County,Indiana,12,7
Perry County,Indiana,12,7
Pike County,Indiana,11,7
Porter County,Indiana,13,7
Posey County,Indiana,12,7
Pulaski County,Indiana,14,7
Putnam County,Indiana,13,7
Randolph County,Indiana,15,7
Ripley County,Indiana,13,7
Rush County,Indiana,11,7
Scott County,Indiana,12,7
Shelby County,Indiana,13,7
Spencer County,Indiana,14,7
St. Joseph County,Indiana,17,7
Starke County,Indiana,13,7
Steuben County,Indiana,14,7
Sullivan County,Indiana,15,7
Switzerland County,Indiana,18,7
Tippecanoe County,Indiana,17,7
Tipton County,Indiana,13,7
Union County,Indiana,12,7
Vanderburgh County,Indiana,18,7
Vermillion County,Indiana,17,7
Vigo County,Indiana,11,7
Wabash County,Indiana,13,7
Warren County,Indiana,13,7
Warrick County,Indiana,14,7
Washington County,Indiana,17,7
Wayne County,Indiana,12,7
Wells County,Indiana,12,7
White County,Indiana,12,7
Whitley County,Indiana,14,7
Adair County,Iowa,12,4
Adams County,Iowa,12,4
Allamakee County,Iowa,16,4
Appanoose County,Iowa,16,4
Audubon County,Iowa,14,4
Benton County,Iowa,13,4
Black Hawk County,Iowa,17,4
Boone County,Iowa,12,4
Bremer County,Iowa,13,4
Buchanan County,Iowa,15,4
Buena Vista County,Iowa,18,4
Butler County,Iowa,13,4
Calhoun County,Iowa,14,4
Carroll County,Iowa,14,4
Cass County,Iowa,11,4
Cedar County,Iowa,12,4
Cerro Gordo County,Iowa,18,4
Cherokee County,Iowa,15,4
Chickasaw County,Iowa,16,4
Clarke County,Iowa,13,4
Clay County,Iowa,11,4
Clayton County,Iowa,14,4
Clinton County,Iowa,14,4
Crawford County,Iowa,15,4
Dallas County,Iowa,13,4
Davis County,Iowa,12,4
Decatur County,Iowa,14,4
Delaware County,Iowa,15,4
Des Moines County,Iowa,17,4
Dickinson County,Iowa,16,4
Dubuque County,Iowa,14,4
Emmet County,Iowa,12,4
Fayette County,Iowa,14,4
Floyd County,Iowa,12,4
Franklin County,Iowa,15,4
Fremont County,Iowa,14,4
Greene County,Iowa,13,4
Grundy County,Iowa,13,4
Guthrie County,Iowa,14,4
Hamilton County,Iowa,15,4
Hancock County,Iowa,14,4
Hardin County,Iowa,13,4
Harrison County,Iowa,15,4
Henry County,Iowa,12,4
Howard County,Iowa,13,4
Humboldt County,Iowa,15,4
Ida County,Iowa,10,4
Iowa County,Iowa,11,4
Jackson County,Iowa,14,4
Jasper County,Iowa,13,4
Jefferson County,Iowa,16,4
Johnson County,Iowa,14,4
Jones County,Iowa,12,4
Keokuk County,Iowa,13,4
Kossuth County,Iowa,14,4
Lee County,Iowa,10,4
Linn County,Iowa,11,4
Louisa County,Iowa,13,4
Lucas County,Iowa,12,4
Lyon County,Iowa,11,4
Madison County,Iowa,14,4
Mahaska County,Iowa,14,4
Marion County,Iowa,13,4
Marshall County,Iowa,15,4
Mills County,Iowa,12,4
Mitchell County,Iowa,15,4
Monona County,Iowa,13,4
Monroe County,Iowa,13,4
Montgomery County,Iowa,17,4
Muscatine County,Iowa,16,4
O'Brien County,Iowa,14,4
Osceola County,Iowa,14,4
Page County,Iowa,11,4
Palo Alto County,Iowa,16,4
Plymouth County,Iowa,15,4
Pocahontas County,Iowa,17,4
Polk County,Iowa,11,4
Pottawattamie County,Iowa,20,4
Poweshiek County,Iowa,16,4
Ringgold County,Iowa,15,4
Sac County,Iowa,10,4
Scott County,Iowa,12,4
Shelby County,Iowa,13,4
Sioux County,Iowa,12,4
Story County,Iowa,12,4
Tama County,Iowa,11,4
Taylor County,Iowa,13,4
Union County,Iowa,12,4
Van Buren County,Iowa,16,4
Wapello County,Iowa,14,4
Warren County,Iowa,13,4
Washington County,Iowa,17,4
Wayne County,Iowa,12,4
Webster County,Iowa,14,4
Winnebago County,Iowa,16,4
Winneshiek County,Iowa,17,4
Woodbury County,Iowa,15,4
Worth County,Iowa,12,4
Wright County,Iowa,13,4
Allen County,Kansas,12,6
Anderson County,Kansas,15,6
Atchison County,Kansas,15,6
Barber County,Kansas,13,6
Barton County,Kansas,13,6
Bourbon County,Kansas,14,6
Brown County,Kansas,12,6
Butler County,Kansas,13,6
Chase County,Kansas,12,6
Chautauqua County,Kansas,17,6
Cherokee County,Kansas,15,6
Cheyenne County,Kansas,15,6
Clark County,Kansas,12,6
Clay County,Kansas,11,6
Cloud County,Kansas,12,6
Coffey County,Kansas,13,6
Comanche County,Kansas,15,6
Cowley County,Kansas,13,6
Crawford County,Kansas,15,6
Decatur County,Kansas,14,6
Dickinson County,Kansas,16,6
Doniphan County,Kansas,15,6
Douglas County,Kansas,14,6
Edwards County,Kansas,14,6
Elk County,Kansas,10,6
Ellis County,Kansas,12,6
Ellsworth County,Kansas,16,6
Finney County,Kansas,13,6
Ford County,Kansas,11,6
Franklin County,Kansas,15,6
Geary County,Kansas,12,6
Gove County,Kansas,11,6
Graham County,Kansas,13,6
Grant County,Kansas,12,6
Gray County,Kansas,11,6
Greeley County,Kansas,14,6
Greenwood County,Kansas,16,6
Hamilton County,Kansas,15,6
Harper County,Kansas,13,6
Harvey County,Kansas,13,6
Haskell County,Kansas,14,6
Hodgeman County,Kansas,15,6
Jackson County,Kansas,14,6
Jefferson County,Kansas,16,6
Jewell County,Kansas,13,6
Johnson County,Kansas,14,6
Kearny County,Kansas,13,6
Kingman County,Kansas,14,6
Kiowa County,Kansas,12,6
Labette County,Kansas,14,6
Lane County,Kansas,11,6
Leavenworth County,Kansas,18,6
Lincoln County,Kansas,14,6
Linn County,Kansas,11,6
Logan County,Kansas,12,6
Lyon County,Kansas,11,6
Marion County,Kansas,13,6
Marshall County,Kansas,15,6
McPherson County,Kansas,16,6
Meade County,Kansas,12,6
Miami County,Kansas,12,6
Mitchell County,Kansas,15,6
Montgomery County,Kansas,17,6
Morris County,Kansas,13,6
Morton County,Kansas,13,6
Nemaha County,Kansas,13,6
Neosho County,Kansas,13,6
Ness County,Kansas,11,6
Norton County,Kansas,13,6
Osage County,Kansas,12,6
Osborne County,Kansas,14,6
Ottawa County,Kansas,13,6
Pawnee County,Kansas,13,6
Phillips County,Kansas,15,6
Pottawatomie County,Kansas,19,6
Pratt County,Kansas,12,6
Rawlins County,Kansas,14,6
Reno County,Kansas,11,6
Republic County,Kansas,15,6
Rice County,Kansas,11,6
Riley County,Kansas,12,6
Rooks County,Kansas,12,6
Rush County,Kansas,11,6
Russell County,Kansas,14,6
Saline County,Kansas,13,6
Scott County,Kansas,12,6
Sedgwick County,Kansas,15,6
Seward County,Kansas,13,6
Shawnee County,Kansas,14,6
Sheridan County,Kansas,15,6
Sherman County,Kansas,14,6
Smith County,Kansas,12,6
Stafford County,Kansas,15,6
Stanton County,Kansas,14,6
Stevens County,Kansas,14,6
Sumner County,Kansas,13,6
Thomas County,Kansas,13,6
Trego County,Kansas,12,6
Wabaunsee County,Kansas,16,6
Wallace County,Kansas,14,6
Washington County,Kansas,17,6
Wichita County,Kansas,14,6
Wilson County,Kansas,13,6
Woodson County,Kansas,14,6
Wyandotte County,Kansas,16,6
Adair County,Kentucky,12,8
Allen County,Kentucky,12,8
Anderson County,Kentucky,15,8
Ballard County,Kentucky,14,8
Barren County,Kentucky,13,8
Bath County,Kentucky,11,8
Bell County,Kentucky,11,8
Boone County,Kentucky,12,8
Bourbon County,Kentucky,14,8
Boyd County,Kentucky,11,8
Boyle County,Kentucky,12,8
Bracken County,Kentucky,14,8
Breathitt County,Kentucky,16,8
Breckinridge County,Kentucky,19,8
Bullitt County,Kentucky,14,8
Butler County,Kentucky,13,8
Caldwell County,Kentucky,15,8
Calloway County,Kentucky,15,8
Campbell County,Kentucky,15,8
Carlisle County,Kentucky,15,8
Carroll County,Kentucky,14,8
Carter County,Kentucky,13,8
Casey County,Kentucky,12,8
Christian County,Kentucky,16,8
Clark County,Kentucky,12,8
Clay County,Kentucky,11,8
Clinton County,Kentucky,14,8
Crittenden County,Kentucky,17,8
Cumberland County,Kentucky,17,8
Daviess County,Kentucky,14,8
Edmonson County,Kentucky,15,8
Elliott County,Kentucky,14,8
Estill County,Kentucky,13,8
Fayette County,Kentucky,14,8
Fleming County,Kentucky,14,8
Floyd County,Kentucky,12,8
Franklin County,Kentucky,15,8
Fulton County,Kentucky,13,8
Gallatin County,Kentucky,15,8
Garrard County,Kentucky,14,8
Grant County,Kentucky,12,8
Graves County,Kentucky,13,8
Grayson County,Kentucky,14,8
Green County,Kentucky,12,8
Greenup County,Kentucky,14,8
Hancock County,Kentucky,14,8
Hardin County,Kentucky,13,8
Harlan County,Kentucky,13,8
Harrison County,Kentucky,15,8
Hart County,Kentucky,11,8
Henderson County,Kentucky,16,8
Henry County,Kentucky,12,8
Hickman County,Kentucky,14,8
Hopkins County,Kentucky,14,8
Jackson County,Kentucky,14,8
Jefferson County,Kentucky,16,8
Jessamine County,Kentucky,16,8
Johnson County,Kentucky,14,8
Kenton County,Kentucky,13,8
Knott County,Kentucky,12,8
Knox County,Kentucky,11,8
Larue County,Kentucky,12,8
Laurel County,Kentucky,13,8
Lawrence County,Kentucky,15,8
Lee County,Kentucky,10,8
Leslie County,Kentucky,13,8
Letcher County,Kentucky,14,8
Lewis County,Kentucky,12,8
Lincoln County,Kentucky,14,8
Livingston County,Kentucky,17,8
Logan County,Kentucky,12,8
Lyon County,Kentucky,11,8
Madison County,Kentucky,14,8
Magoffin County,Kentucky,15,8
Marion County,Kentucky,13,8
Marshall County,Kentucky,15,8
Martin County,Kentucky,13,8
Mason County,Kentucky,12,8
McCracken County,Kentucky,16,8
McCreary County,Kentucky,15,8
McLean County,Kentucky,13,8
Meade County,Kentucky,12,8
Menifee County,Kentucky,14,8
Mercer County,Kentucky,13,8
Metcalfe County,Kentucky,15,8
Monroe County,Kentucky,13,8
Montgomery County,Kentucky,17,8
Morgan County,Kentucky,13,8
Muhlenberg County,Kentucky,17,8
Nelson County,Kentucky,13,8
Nicholas County,Kentucky,15,8
Ohio County,Kentucky,11,8
Oldham County,Kentucky,13,8
Owen County,Kentucky,11,8
Owsley County,Kentucky,13,8
Pendleton County,Kentucky,16,8
Perry County,Kentucky,12,8
Pike County,Kentucky,11,8
Powell County,Kentucky,13,8
Pulaski County,Kentucky,14,8
Robertson County,Kentucky,16,8
Rockcastle County,Kentucky,17,8
Rowan County,Kentucky,12,8
Russell County,Kentucky,14,8
Scott County,Kentucky,12,8
Shelby County,Kentucky,13,8
Simpson County,Kentucky,14,8
Spencer County,Kentucky,14,8
Taylor County,Kentucky,13,8
Todd County,Kentucky,11,8
Trigg County,Kentucky,12,8
Trimble County,Kentucky,14,8
Union County,Kentucky,12,8
Warren County,Kentucky,13,8
Washington County,Kentucky,17,8
Wayne County,Kentucky,12,8
Webster County,Kentucky,14,8
Whitley County,Kentucky,14,8
Wolfe County,Kentucky,12,8
Woodford County,Kentucky,15,8
Acadia Parish,Louisiana,13,9
Allen Parish,Louisiana,12,9
Ascension Parish,Louisiana,16,9
Assumption Parish,Louisiana,17,9
Avoyelles Parish,Louisiana,16,9
Beauregard Parish,Louisiana,17,9
Bienville Parish,Louisiana,16,9
Bossier Parish,Louisiana,14,9
Caddo Parish,Louisiana,12,9
Calcasieu Parish,Louisiana,16,9
Caldwell Parish,Louisiana,15,9
Cameron Parish,Louisiana,14,9
Catahoula Parish,Louisiana,16,9
Claiborne Parish,Louisiana,16,9
Concordia Parish,Louisiana,16,9
De Soto Parish,Louisiana,14,9
East Baton Rouge Parish,Louisiana,23,9
East Carroll Parish,Louisiana,19,9
East Feliciana Parish,Louisiana,21,9
Evangeline Parish,Louisiana,17,9
Franklin Parish,Louisiana,15,9
Grant Parish,Louisiana,12,9
Iberia Parish,Louisiana,13,9
Iberville Parish,Louisiana,16,9
Jackson Parish,Louisiana,14,9
Jefferson Parish,Louisiana,16,9
Jefferson Davis Parish,Louisiana,22,9
La Salle Parish,Louisiana,15,9
Lafayette Parish,Louisiana,16,9
Lafourche Parish,Louisiana,16,9
Lincoln Parish,Louisiana,14,9
Livingston Parish,Louisiana,17,9
Madison Parish,Louisiana,14,9
Morehouse Parish,Louisiana,16,9
Natchitoches Parish,Louisiana,19,9
Orleans Parish,Louisiana,14,9
Ouachita Parish,Louisiana,15,9
Plaquemines Parish,Louisiana,18,9
Pointe Coupee Parish,Louisiana,20,9
Rapides Parish,Louisiana,14,9
Red River Parish,Louisiana,16,9
Richland Parish,Louisiana,15,9
Sabine Parish,Louisiana,13,9
St. Bernard Parish,Louisiana,18,9
St. Charles Parish,Louisiana,18,9
St. Helena Parish,Louisiana,17,9
St. James Parish,Louisiana,16,9
St. John the Baptist Parish,Louisiana,27,9
St. Landry Parish,Louisiana,17,9
St. Martin Parish,Louisiana,17,9
St. Mary Parish,Louisiana,15,9
St. Tammany Parish,Louisiana,18,9
Tangipahoa Parish,Louisiana,17,9
Tensas Parish,Louisiana,13,9
Terrebonne Parish,Louisiana,17,9
Union Parish,Louisiana,12,9
Vermilion Parish,Louisiana,16,9
Vernon Parish,Louisiana,13,9
Washington Parish,Louisiana,17,9
Webster Parish,Louisiana,14,9
West Baton Rouge Parish,Louisiana,23,9
West Carroll Parish,Louisiana,19,9
West Feliciana Parish,Louisiana,21,9
Winn Parish,Louisiana,11,9
Androscoggin County,Maine,19,5
Aroostook County,Maine,16,5
Cumberland County,Maine,17,5
Franklin County,Maine,15,5
Hancock County,Maine,14,5
Kennebec County,Maine,15,5
Knox County,Maine,11,5
Lincoln County,Maine,14,5
Oxford County,Maine,13,5
Penobscot County,Maine,16,5
Piscataquis County,Maine,18,5
Sagadahoc County,Maine,16,5
Somerset County,Maine,15,5
Waldo County,Maine,12,5
Washington County,Maine,17,5
York County,Maine,11,5
Allegany County,Maryland,15,8
Anne Arundel County,Maryland,19,8
Baltimore County,Maryland,16,8
Calvert County,Maryland,14,8
Caroline County,Maryland,15,8
Carroll County,Maryland,14,8
Cecil County,Maryland,12,8
Charles County,Maryland,14,8
Dorchester County,Maryland,17,8
Frederick County,Maryland,16,8
Garrett County,Maryland,14,8
Harford County,Maryland,14,8
Howard County,Maryland,13,8
Kent County,Maryland,11,8
Montgomery County,Maryland,17,8
Prince George's County,Maryland,22,8
Queen Anne's County,Maryland,19,8
Somerset County,Maryland,15,8
St. Mary's County,Maryland,17,8
Talbot County,Maryland,13,8
Washington County,Maryland,17,8
Wicomico County,Maryland,15,8
Worcester County,Maryland,16,8
Barnstable County,Massachusetts,17,13
Berkshire County,Massachusetts,16,13
Bristol County,Massachusetts,14,13
Dukes County,Massachusetts,12,13
Essex County,Massachusetts,12,13
Franklin County,Massachusetts,15,13
Hampden County,Massachusetts,14,13
Hampshire County,Massachusetts,16,13
Middlesex County,Massachusetts,16,13
Nantucket County,Massachusetts,16,13
Norfolk County,Massachusetts,14,13
Plymouth County,Massachusetts,15,13
Suffolk County,Massachusetts,14,13
Worcester County,Massachusetts,16,13
Alcona County,Michigan,13,8
Alger County,Michigan,12,8
Allegan County,Michigan,14,8
Alpena County,Michigan,13,8
Antrim County,Michigan,13,8
Arenac County,Michigan,13,8
Baraga County,Michigan,13,8
Barry County,Michigan,12,8
Bay County,Michigan,10,8
Benzie County,Michigan,13,8
Berrien County,Michigan,14,8
Branch County,Michigan,13,8
Calhoun County,Michigan,14,8
Cass County,Michigan,11,8
Charlevoix County,Michigan,17,8
Cheboygan County,Michigan,16,8
Chippewa County,Michigan,15,8
Clare County,Michigan,12,8
Clinton County,Michigan,14,8
Crawford County,Michigan,15,8
Delta County,Michigan,12,8
Dickinson County,Michigan,16,8
Eaton County,Michigan,12,8
Emmet County,Michigan,12,8
Genesee County,Michigan,14,8
Gladwin County,Michigan,14,8
Gogebic County,Michigan,14,8
Grand Traverse County,Michigan,21,8
Gratiot County,Michigan,14,8
Hillsdale County,Michigan,16,8
Houghton County,Michigan,15,8
Huron County,Michigan,12,8
Ingham County,Michigan,13,8
Ionia County,Michigan,12,8
Iosco County,Michigan,12,8
Iron County,Michigan,11,8
Isabella County,Michigan,15,8
Jackson County,Michigan,14,8
Kalamazoo County,Michigan,16,8
Kalkaska County,Michigan,15,8
Kent County,Michigan,11,8
Keweenaw County,Michigan,15,8
Lake County,Michigan,11,8
Lapeer County,Michigan,13,8
Leelanau County,Michigan,15,8
Lenawee County,Michigan,14,8
Livingston County,Michigan,17,8
Luce County,Michigan,11,8
Mackinac County,Michigan,15,8
Macomb County,Michigan,13,8
Manistee County,Michigan,15,8
Marquette County,Michigan,16,8
Mason County,Michigan,12,8
Mecosta County,Michigan,14,8
Menominee County,Michigan,16,8
Midland County,Michigan,14,8
Missaukee County,Michigan,16,8
Monroe County,Michigan,13,8
Montcalm County,Michigan,15,8
Montmorency County,Michigan,18,8
Muskegon County,Michigan,15,8
Newaygo County,Michigan,14,8
Oakland County,Michigan,14,8
Oceana County,Michigan,13,8
Ogemaw County,Michigan,13,8
Ontonagon County,Michigan,16,8
Osceola County,Michigan,14,8
Oscoda County,Michigan,13,8
Otsego County,Michigan,13,8
Ottawa County,Michigan,13,8
Presque Isle County,Michigan,19,8
Roscommon County,Michigan,16,8
Saginaw County,Michigan,14,8
Sanilac County,Michigan,14,8
Schoolcraft County,Michigan,18,8
Shiawassee County,Michigan,17,8
St. Clair County,Michigan,16,8
St. Joseph County,Michigan,17,8
Tuscola County,Michigan,14,8
Van Buren County,Michigan,16,8
Washtenaw County,Michigan,16,8
Wayne County,Michigan,12,8
Wexford County,Michigan,14,8
Aitkin County,Minnesota,13,9
Anoka County,Minnesota,12,9
Becker County,Minnesota,13,9
Beltrami County,Minnesota,15,9
Benton County,Minnesota,13,9
Big Stone County,Minnesota,16,9
Blue Earth County,Minnesota,17,9
Brown County,Minnesota,12,9
Carlton County,Minnesota,14,9
Carver County,Minnesota,13,9
Cass County,Minnesota,11,9
Chippewa County,Minnesota,15,9
Chisago County,Minnesota,14,9
Clay County,Minnesota,11,9
Clearwater County,Minnesota,17,9
Cook County,Minnesota,11,9
Cottonwood County,Minnesota,17,9
Crow Wing County,Minnesota,16,9
Dakota County,Minnesota,13,9
Dodge County,Minnesota,12,9
Douglas County,Minnesota,14,9
Faribault County,Minnesota,16,9
Fillmore County,Minnesota,15,9
Freeborn County,Minnesota,15,9
Goodhue County,Minnesota,14,9
Grant County,Minnesota,12,9
Hennepin County,Minnesota,15,9
Houston County,Minnesota,14,9
Hubbard County,Minnesota,14,9
Isanti County,Minnesota,13,9
Itasca County,Minnesota,13,9
Jackson County,Minnesota,14,9
Kanabec County,Minnesota,14,9
Kandiyohi County,Minnesota,16,9
Kittson County,Minnesota,14,9
Koochiching County,Minnesota,18,9
Lac qui Parle County,Minnesota,20,9
Lake County,Minnesota,11,9
Lake of the Woods County,Minnesota,24,9
Le Sueur County,Minnesota,15,9
Lincoln County,Minnesota,14,9
Lyon County,Minnesota,11,9
Mahnomen County,Minnesota,15,9
Marshall County,Minnesota,15,9
Martin County,Minnesota,13,9
McLeod County,Minnesota,13,9
Meeker County,Minnesota,13,9
Mille Lacs County,Minnesota,17,9
Morrison County,Minnesota,15,9
Mower County,Minnesota,12,9
Murray County,Minnesota,13,9
Nicollet County,Minnesota,15,9
Nobles County,Minnesota,13,9
Norman County,Minnesota,13,9
Olmsted County,Minnesota,14,9
Otter Tail County,Minnesota,17,9
Pennington County,Minnesota,17,9
Pine County,Minnesota,11,9
Pipestone County,Minnesota,16,9
Polk County,Minnesota,11,9
Pope County,Minnesota,11,9
Ramsey County,Minnesota,13,9
Red Lake County,Minnesota,15,9
Redwood County,Minnesota,14,9
Renville County,Minnesota,15,9
Rice County,Minnesota,11,9
Rock County,Minnesota,11,9
Roseau County,Minnesota,13,9
Scott County,Minnesota,12,9
Sherburne County,Minnesota,16,9
Sibley County,Minnesota,13,9
St. Louis County,Minnesota,16,9
Stearns County,Minnesota,14,9
Steele County,Minnesota,13,9
Stevens County,Minnesota,14,9
Swift County,Minnesota,12,9
Todd County,Minnesota,11,9
Traverse County,Minnesota,15,9
Wabasha County,Minnesota,14,9
Wadena County,Minnesota,13,9
Waseca County,Minnesota,13,9
Washington County,Minnesota,17,9
Watonwan County,Minnesota,15,9
Wilkin County,Minnesota,13,9
Winona County,Minnesota,13,9
Wright County,Minnesota,13,9
Yellow Medicine County,Minnesota,22,9
Adams County,Mississippi,12,11
Alcorn County,Mississippi,13,11
Amite County,Mississippi,12,11
Attala County,Mississippi,13,11
Benton County,Mississippi,13,11
Bolivar County,Mississippi,14,11
Calhoun County,Mississippi,14,11
Carroll County,Mississippi,14,11
Chickasaw County,Mississippi,16,11
Choctaw County,Mississippi,14,11
Claiborne County,Mississippi,16,11
Clarke County,Mississippi,13,11
Clay County,Mississippi,11,11
Coahoma County,Mississippi,14,11
Copiah County,Mississippi,13,11
Covington County,Mississippi,16,11
De Soto County,Mississippi,14,11
Forrest County,Mississippi,14,11
Franklin County,Mississippi,15,11
George County,Mississippi,13,11
Greene County,Mississippi,13,11
Grenada County,Mississippi,14,11
Hancock County,Mississippi,14,11
Harrison County,Mississippi,15,11
Hinds County,Mississippi,12,11
Holmes County,Mississippi,13,11
Humphreys County,Mississippi,16,11
Issaquena County,Mississippi,16,11
Itawamba County,Mississippi,15,11
Jackson County,Mississippi,14,11
Jasper County,Mississippi,13,11
Jefferson County,Mississippi,16,11
Jefferson Davis County,Mississippi,22,11
Jones County,Mississippi,12,11
Kemper County,Mississippi,13,11
Lafayette County,Mississippi,16,11
Lamar County,Mississippi,12,11
Lauderdale County,Mississippi,17,11
Lawrence County,Mississippi,15,11
Leake County,Mississippi,12,11
Lee County,Mississippi,10,11
Leflore County,Mississippi,14,11
Lincoln County,Mississippi,14,11
Lowndes County,Mississippi,14,11
Madison County,Mississippi,14,11
Marion County,Mississippi,13,11
Marshall County,Mississippi,15,11
Monroe County,Mississippi,13,11
Montgomery County,Mississippi,17,11
Neshoba County,Mississippi,14,11
Newton County,Mississippi,13,11
Noxubee County,Mississippi,14,11
Oktibbeha County,Mississippi,16,11
Panola County,Mississippi,13,11
Pearl River County,Mississippi,18,11
Perry County,Mississippi,12,11
Pike County,Mississippi,11,11
Pontotoc County,Mississippi,15,11
Prentiss County,Mississippi,15,11
Quitman County,Mississippi,14,11
Rankin County,Mississippi,13,11
Scott County,Mississippi,12,11
Sharkey County,Mississippi,14,11
Simpson County,Mississippi,14,11
Smith County,Mississippi,12,11
Stone County,Mississippi,12,11
Sunflower County,Mississippi,16,11
Tallahatchie County,Mississippi,19,11
Tate County,Mississippi,11,11
Tippah County,Mississippi,13,11
Tishomingo County,Mississippi,17,11
Tunica County,Mississippi,13,11
Union County,Mississippi,12,11
Walthall County,Mississippi,15,11
Warren County,Mississippi,13,11
Washington County,Mississippi,17,11
Wayne County,Mississippi,12,11
Webster County,Mississippi,14,11
Wilkinson County,Mississippi,16,11
Winston County,Mississippi,14,11
Yalobusha County,Mississippi,16,11
Yazoo County,Mississippi,12,11
Adair County,Missouri,12,8
Andrew County,Missouri,13,8
Atchison County,Missouri,15,8
Audrain County,Missouri,14,8
Barry County,Missouri,12,8
Barton County,Missouri,13,8
Bates County,Missouri,12,8
Benton County,Missouri,13,8
Bollinger County,Missouri,16,8
Boone County,Missouri,12,8
Buchanan County,Missouri,15,8
Butler County,Missouri,13,8
Caldwell County,Missouri,15,8
Callaway County,Missouri,15,8
Camden County,Missouri,13,8
Cape Girardeau County,Missouri,21,8
Carroll County,Missouri,14,8
Carter County,Missouri,13,8
Cass County,Missouri,11,8
Cedar County,Missouri,12,8
Chariton County,Missouri,15,8
Christian County,Missouri,16,8
Clark County,Missouri,12,8
Clay County,Missouri,11,8
Clinton County,Missouri,14,8
Cole County,Missouri,11,8
Cooper County,Missouri,13,8
Crawford County,Missouri,15,8
Dade County,Missouri,11,8
Dallas County,Missouri,13,8
Daviess County,Missouri,14,8
DeKalb County,Missouri,13,8
Dent County,Missouri,11,8
Douglas County,Missouri,14,8
Dunklin County,Missouri,14,8
Franklin County,Missouri,15,8
Gasconade County,Missouri,16,8
Gentry County,Missouri,13,8
Greene County,Missouri,13,8
Grundy County,Missouri,13,8
Harrison County,Missouri,15,8
Henry County,Missouri,12,8
Hickory County,Missouri,14,8
Holt County,Missouri,11,8
Howard County,Missouri,13,8
Howell County,Missouri,13,8
Iron County,Missouri,11,8
Jackson County,Missouri,14,8
Jasper County,Missouri,13,8
Jefferson County,Missouri,16,8
Johnson County,Missouri,14,8
Knox County,Missouri,11,8
Laclede County,Missouri,14,8
Lafayette County,Missouri,16,8
Lawrence County,Missouri,15,8
Lewis County,Missouri,12,8
Lincoln County,Missouri,14,8
Linn County,Missouri,11,8
Livingston County,Missouri,17,8
Macon County,Missouri,12,8
Madison County,Missouri,14,8
Maries County,Missouri,13,8
Marion County,Missouri,13,8
McDonald County,Missouri,15,8
Mercer County,Missouri,13,8
Miller County,Missouri,13,8
Mississippi County,Missouri,18,8
Moniteau County,Missouri,15,8
Monroe County,Missouri,13,8
Montgomery County,Missouri,17,8
Morgan County,Missouri,13,8
New Madrid County,Missouri,17,8
Newton County,Missouri,13,8
Nodaway County,Missouri,14,8
Oregon County,Missouri,13,8
Osage County,Missouri,12,8
Ozark County,Missouri,12,8
Pemiscot County,Missouri,15,8
Perry County,Missouri,12,8
Pettis County,Missouri,13,8
Phelps County,Missouri,13,8
Pike County,Missouri,11,8
Platte County,Missouri,13,8
Polk County,Missouri,11,8
Pulaski County,Missouri,14,8
Putnam County,Missouri,13,8
Ralls County,Missouri,12,8
Randolph County,Missouri,15,8
Ray County,Missouri,10,8
Reynolds County,Missouri,15,8
Ripley County,Missouri,13,8
Saline County,Missouri,13,8
Schuyler County,Missouri,15,8
Scotland County,Missouri,15,8
Scott County,Missouri,12,8
Shannon County,Missouri,14,8
Shelby County,Missouri,13,8
St. Charles County,Missouri,18,8
St. Clair County,Missouri,16,8
St. Francois County,Missouri,19,8
St. Louis County,Missouri,16,8
Ste. Genevieve County,Missouri,21,8
Stoddard County,Missouri,15,8
Stone County,Missouri,12,8
Sullivan County,Missouri,15,8
Taney County,Missouri,12,8
Texas County,Missouri,12,8
Vernon County,Missouri,13,8
Warren County,Missouri,13,8
Washington County,Missouri,17,8
Wayne County,Missouri,12,8
Webster County,Missouri,14,8
Worth County,Missouri,12,8
Wright County,Missouri,13,8
Beaverhead County,Montana,17,7
Big Horn County,Montana,15,7
Blaine County,Montana,13,7
Broadwater County,Montana,17,7
Carbon County,Montana,13,7
Carter County,Montana,13,7
Cascade County,Montana,14,7
Chouteau County,Montana,15,7
Custer County,Montana,13,7
Daniels County,Montana,14,7
Dawson County,Montana,13,7
Deer Lodge County,Montana,17,7
Fallon County,Montana,13,7
Fergus County,Montana,13,7
Flathead County,Montana,15,7
Gallatin County,Montana,15,7
Garfield County,Montana,15,7
Glacier County,Montana,14,7
Golden Valley County,Montana,20,7
Granite County,Montana,14,7
Hill County,Montana,11,7
Jefferson County,Montana,16,7
Judith Basin County,Montana,19,7
Lake County,Montana,11,7
Lewis and Clark County,Montana,22,7
Liberty County,Montana,14,7
Lincoln County,Montana,14,7
Madison County,Montana,14,7
McCone County,Montana,13,7
Meagher County,Montana,14,7
Mineral County,Montana,14,7
Missoula County,Montana,15,7
Musselshell County,Montana,18,7
Park County,Montana,11,7
Petroleum County,Montana,16,7
Phillips County,Montana,15,7
Pondera County,Montana,14,7
Powder River County,Montana,19,7
Powell County,Montana,13,7
Prairie County,Montana,14,7
Ravalli County,Montana,14,7
Richland County,Montana,15,7
Roosevelt County,Montana,16,7
Rosebud County,Montana,14,7
Sanders County,Montana,14,7
Sheridan County,Montana,15,7
Silver Bow County,Montana,17,7
Stillwater County,Montana,17,7
Sweet Grass County,Montana,18,7
Teton County,Montana,12,7
Toole County,Montana,12,7
Treasure County,Montana,15,7
Valley County,Montana,13,7
Wheatland County,Montana,16,7
Wibaux County,Montana,13,7
Yellowstone County,Montana,18,7
Platte County,Nebraska,13,8
Adams County,Nebraska,12,8
Antelope County,Nebraska,15,8
Arthur County,Nebraska,13,8
Banner County,Nebraska,13,8
Blaine County,Nebraska,13,8
Boone County,Nebraska,12,8
Box Butte County,Nebraska,16,8
Boyd County,Nebraska,11,8
Brown County,Nebraska,12,8
Buffalo County,Nebraska,14,8
Burt County,Nebraska,11,8
Butler County,Nebraska,13,8
Cass County,Nebraska,11,8
Cedar County,Nebraska,12,8
Chase County,Nebraska,12,8
Cherry County,Nebraska,13,8
Cheyenne County,Nebraska,15,8
Clay County,Nebraska,11,8
Colfax County,Nebraska,13,8
Cuming County,Nebraska,13,8
Custer County,Nebraska,13,8
Dakota County,Nebraska,13,8
Dawes County,Nebraska,12,8
Dawson County,Nebraska,13,8
Deuel County,Nebraska,12,8
Dixon County,Nebraska,12,8
Dodge County,Nebraska,12,8
Douglas County,Nebraska,14,8
Dundy County,Nebraska,12,8
Fillmore County,Nebraska,15,8
Franklin County,Nebraska,15,8
Frontier County,Nebraska,15,8
Furnas County,Nebraska,13,8
Gage County,Nebraska,11,8
Garden County,Nebraska,13,8
Garfield County,Nebraska,15,8
Gosper County,Nebraska,13,8
Grant County,Nebraska,12,8
Greeley County,Nebraska,14,8
Hall County,Nebraska,11,8
Hamilton County,Nebraska,15,8
Harlan County,Nebraska,13,8
Hayes County,Nebraska,12,8
Hitchcock County,Nebraska,16,8
Holt County,Nebraska,11,8
Hooker County,Nebraska,13,8
Howard County,Nebraska,13,8
Jefferson County,Nebraska,16,8
Johnson County,Nebraska,14,8
Kearney County,Nebraska,14,8
Keith County,Nebraska,12,8
Keya Paha County,Nebraska,16,8
Kimball County,Nebraska,14,8
Knox County,Nebraska,11,8
Lancaster County,Nebraska,16,8
Lincoln County,Nebraska,14,8
Logan County,Nebraska,12,8
Loup County,Nebraska,11,8
Madison County,Nebraska,14,8
McPherson County,Nebraska,16,8
Merrick County,Nebraska,14,8
Morrill County,Nebraska,14,8
Nance County,Nebraska,12,8
Nemaha County,Nebraska,13,8
Nuckolls County,Nebraska,15,8
Otoe County,Nebraska,11,8
Pawnee County,Nebraska,13,8
Perkins County,Nebraska,14,8
Phelps County,Nebraska,13,8
Pierce County,Nebraska,13,8
Polk County,Nebraska,11,8
Red Willow County,Nebraska,17,8
Richardson County,Nebraska,17,8
Rock County,Nebraska,11,8
Saline County,Nebraska,13,8
Sarpy County,Nebraska,12,8
Saunders County,Nebraska,15,8
Scotts Bluff County,Nebraska,19,8
Seward County,Nebraska,13,8
Sheridan County,Nebraska,15,8
Sherman County,Nebraska,14,8
Sioux County,Nebraska,12,8
Stanton County,Nebraska,14,8
Thayer County,Nebraska,13,8
Thomas County,Nebraska,13,8
Thurston County,Nebraska,15,8
Valley County,Nebraska,13,8
Washington County,Nebraska,17,8
Wayne County,Nebraska,12,8
Webster County,Nebraska,14,8
Wheeler County,Nebraska,14,8
York County,Nebraska,11,8
Churchill County,Nevada,16,6
Clark County,Nevada,12,6
Douglas County,Nevada,14,6
Elko County,Nevada,11,6
Esmeralda County,Nevada,16,6
Eureka County,Nevada,13,6
Humboldt County,Nevada,15,6
Lander County,Nevada,13,6
Lincoln County,Nevada,14,6
Lyon County,Nevada,11,6
Mineral County,Nevada,14,6
Nye County,Nevada,10,6
Pershing County,Nevada,15,6
Storey County,Nevada,13,6
Washoe County,Nevada,13,6
White Pine County,Nevada,17,6
Belknap County,New Hampshire,14,13
Carroll County,New Hampshire,14,13
Cheshire County,New Hampshire,15,13
Coos County,New Hampshire,11,13
Grafton County,New Hampshire,14,13
Hillsborough County,New Hampshire,19,13
Merrimack County,New Hampshire,16,13
Rockingham County,New Hampshire,17,13
Strafford County,New Hampshire,16,13
Sullivan County,New Hampshire,15,13
Atlantic County,New Jersey,15,10
Bergen County,New Jersey,13,10
Burlington County,New Jersey,17,10
Camden County,New Jersey,13,10
Cape May County,New Jersey,15,10
Cumberland County,New Jersey,17,10
Essex County,New Jersey,12,10
Gloucester County,New Jersey,17,10
Hudson County,New Jersey,13,10
Hunterdon County,New Jersey,16,10
Mercer County,New Jersey,13,10
Middlesex County,New Jersey,16,10
Monmouth County,New Jersey,15,10
Morris County,New Jersey,13,10
Ocean County,New Jersey,12,10
Passaic County,New Jersey,14,10
Salem County,New Jersey,12,10
Somerset County,New Jersey,15,10
Sussex County,New Jersey,13,10
Union County,New Jersey,12,10
Warren County,New Jersey,13,10
Bernalillo County,New Mexico,17,10
Catron County,New Mexico,13,10
Chaves County,New Mexico,13,10
Cibola County,New Mexico,13,10
Colfax County,New Mexico,13,10
Curry County,New Mexico,12,10
DeBaca County,New Mexico,13,10
Do̱a Ana County,New Mexico,16,10
Eddy County,New Mexico,11,10
Grant County,New Mexico,12,10
Guadalupe County,New Mexico,16,10
Harding County,New Mexico,14,10
Hidalgo County,New Mexico,14,10
Lea County,New Mexico,10,10
Lincoln County,New Mexico,14,10
Los Alamos County,New Mexico,17,10
Luna County,New Mexico,11,10
McKinley County,New Mexico,15,10
Mora County,New Mexico,11,10
Otero County,New Mexico,12,10
Quay County,New Mexico,11,10
Rio Arriba County,New Mexico,17,10
Roosevelt County,New Mexico,16,10
San Juan County,New Mexico,15,10
San Miguel County,New Mexico,17,10
Sandoval County,New Mexico,15,10
Santa Fe County,New Mexico,15,10
Sierra County,New Mexico,13,10
Socorro County,New Mexico,14,10
Taos County,New Mexico,11,10
Torrance County,New Mexico,15,10
Union County,New Mexico,12,10
Valencia County,New Mexico,15,10
Albany County,New York,13,8
Allegany County,New York,15,8
Bronx County,New York,12,8
Broome County,New York,13,8
Cattaraugus County,New York,18,8
Cayuga County,New York,13,8
Chautauqua County,New York,17,8
Chemung County,New York,14,8
Chenango County,New York,15,8
Clinton County,New York,14,8
Columbia County,New York,15,8
Cortland County,New York,15,8
Delaware County,New York,15,8
Dutchess County,New York,15,8
Erie County,New York,11,8
Essex County,New York,12,8
Franklin County,New York,15,8
Fulton County,New York,13,8
Genesee County,New York,14,8
Greene County,New York,13,8
Hamilton County,New York,15,8
Herkimer County,New York,15,8
Jefferson County,New York,16,8
Kings County,New York,12,8
Lewis County,New York,12,8
Livingston County,New York,17,8
Madison County,New York,14,8
Monroe County,New York,13,8
Montgomery County,New York,17,8
Nassau County,New York,13,8
New York County,New York,15,8
Niagara County,New York,14,8
Oneida County,New York,13,8
Onondaga County,New York,15,8
Ontario County,New York,14,8
Orange County,New York,13,8
Orleans County,New York,14,8
Oswego County,New York,13,8
Otsego County,New York,13,8
Putnam County,New York,13,8
Queens County,New York,13,8
Rensselaer County,New York,17,8
Richmond County,New York,15,8
Rockland County,New York,15,8
Saratoga County,New York,15,8
Schenectady County,New York,18,8
Schoharie County,New York,16,8
Schuyler County,New York,15,8
Seneca County,New York,13,8
St. Lawrence County,New York,19,8
Steuben County,New York,14,8
Suffolk County,New York,14,8
Sullivan County,New York,15,8
Tioga County,New York,12,8
Tompkins County,New York,15,8
Ulster County,New York,13,8
Warren County,New York,13,8
Washington County,New York,17,8
Wayne County,New York,12,8
Westchester County,New York,18,8
Wyoming County,New York,14,8
Yates County,New York,12,8
Alamance County,North Carolina,15,14
Alexander County,North Carolina,16,14
Alleghany County,North Carolina,16,14
Anson County,North Carolina,12,14
Ashe County,North Carolina,11,14
Avery County,North Carolina,12,14
Beaufort County,North Carolina,15,14
Bertie County,North Carolina,13,14
Bladen County,North Carolina,13,14
Brunswick County,North Carolina,16,14
Buncombe County,North Carolina,15,14
Burke County,North Carolina,12,14
Cabarrus County,North Carolina,15,14
Caldwell County,North Carolina,15,14
Camden County,North Carolina,13,14
Carteret County,North Carolina,15,14
Caswell County,North Carolina,14,14
Catawba County,North Carolina,14,14
Chatham County,North Carolina,14,14
Cherokee County,North Carolina,15,14
Chowan County,North Carolina,13,14
Clay County,North Carolina,11,14
Cleveland County,North Carolina,16,14
Columbus County,North Carolina,15,14
Craven County,North Carolina,13,14
Cumberland County,North Carolina,17,14
Currituck County,North Carolina,16,14
Dare County,North Carolina,11,14
Davidson County,North Carolina,15,14
Davie County,North Carolina,12,14
Duplin County,North Carolina,13,14
Durham County,North Carolina,13,14
Edgecombe County,North Carolina,16,14
Forsyth County,North Carolina,14,14
Franklin County,North Carolina,15,14
Gaston County,North Carolina,13,14
Gates County,North Carolina,12,14
Graham County,North Carolina,13,14
Granville County,North Carolina,16,14
Greene County,North Carolina,13,14
Guilford County,North Carolina,15,14
Halifax County,North Carolina,14,14
Harnett County,North Carolina,14,14
Haywood County,North Carolina,14,14
Henderson County,North Carolina,16,14
Hertford County,North Carolina,15,14
Hoke County,North Carolina,11,14
Hyde County,North Carolina,11,14
Iredell County,North Carolina,14,14
Jackson County,North Carolina,14,14
Johnston County,North Carolina,15,14
Jones County,North Carolina,12,14
Lee County,North Carolina,10,14
Lenoir County,North Carolina,13,14
Lincoln County,North Carolina,14,14
Macon County,North Carolina,12,14
Madison County,North Carolina,14,14
Martin County,North Carolina,13,14
McDowell County,North Carolina,15,14
Mecklenburg County,North Carolina,18,14
Mitchell County,North Carolina,15,14
Montgomery County,North Carolina,17,14
Moore County,North Carolina,12,14
Nash County,North Carolina,11,14
New Hanover County,North Carolina,18,14
Northampton County,North Carolina,18,14
Onslow County,North Carolina,13,14
Orange County,North Carolina,13,14
Pamlico County,North Carolina,14,14
Pasquotank County,North Carolina,17,14
Pender County,North Carolina,13,14
Perquimans County,North Carolina,17,14
Person County,North Carolina,13,14
Pitt County,North Carolina,11,14
Polk County,North Carolina,11,14
Randolph County,North Carolina,15,14
Richmond County,North Carolina,15,14
Robeson County,North Carolina,14,14
Rockingham County,North Carolina,17,14
Rowan County,North Carolina,12,14
Rutherford County,North Carolina,17,14
Sampson County,North Carolina,14,14
Scotland County,North Carolina,15,14
Stanly County,North Carolina,13,14
Stokes County,North Carolina,13,14
Surry County,North Carolina,12,14
Swain County,North Carolina,12,14
Transylvania County,North Carolina,19,14
Tyrrell County,North Carolina,14,14
Union County,North Carolina,12,14
Vance County,North Carolina,12,14
Wake County,North Carolina,11,14
Warren County,North Carolina,13,14
Washington County,North Carolina,17,14
Watauga County,North Carolina,14,14
Wayne County,North Carolina,12,14
Wilkes County,North Carolina,13,14
Wilson County,North Carolina,13,14
Yadkin County,North Carolina,13,14
Yancey County,North Carolina,13,14
Adams County,North Dakota,12,12
Barnes County,North Dakota,13,12
Benson County,North Dakota,13,12
Billings County,North Dakota,15,12
Bottineau County,North Dakota,16,12
Bowman County,North Dakota,13,12
Burke County,North Dakota,12,12
Burleigh County,North Dakota,15,12
Cass County,North Dakota,11,12
Cavalier County,North Dakota,15,12
Dickey County,North Dakota,13,12
Divide County,North Dakota,13,12
Dunn County,North Dakota,11,12
Eddy County,North Dakota,11,12
Emmons County,North Dakota,13,12
Foster County,North Dakota,13,12
Golden Valley County,North Dakota,20,12
Grand Forks County,North Dakota,18,12
Grant County,North Dakota,12,12
Griggs County,North Dakota,13,12
Hettinger County,North Dakota,16,12
Kidder County,North Dakota,13,12
La Moure County,North Dakota,15,12
Logan County,North Dakota,12,12
McHenry County,North Dakota,14,12
McIntosh County,North Dakota,15,12
McKenzie County,North Dakota,15,12
McLean County,North Dakota,13,12
Mercer County,North Dakota,13,12
Morton County,North Dakota,13,12
Mountrail County,North Dakota,16,12
Nelson County,North Dakota,13,12
Oliver County,North Dakota,13,12
Pembina County,North Dakota,14,12
Pierce County,North Dakota,13,12
Ramsey County,North Dakota,13,12
Ransom County,North Dakota,13,12
Renville County,North Dakota,15,12
Richland County,North Dakota,15,12
Rolette County,North Dakota,14,12
Sargent County,North Dakota,14,12
Sheridan County,North Dakota,15,12
Sioux County,North Dakota,12,12
Slope County,North Dakota,12,12
Stark County,North Dakota,12,12
Steele County,North Dakota,13,12
Stutsman County,North Dakota,15,12
Towner County,North Dakota,13,12
Traill County,North Dakota,13,12
Walsh County,North Dakota,12,12
Ward County,North Dakota,11,12
Wells County,North Dakota,12,12
Williams County,North Dakota,15,12
Adams County,Ohio,12,4
Allen County,Ohio,12,4
Ashland County,Ohio,14,4
Ashtabula County,Ohio,16,4
Athens County,Ohio,13,4
Auglaize County,Ohio,15,4
Belmont County,Ohio,14,4
Brown County,Ohio,12,4
Butler County,Ohio,13,4
Carroll County,Ohio,14,4
Champaign County,Ohio,16,4
Clark County,Ohio,12,4
Clermont County,Ohio,15,4
Clinton County,Ohio,14,4
Columbiana County,Ohio,17,4
Coshocton County,Ohio,16,4
Crawford County,Ohio,15,4
Cuyahoga County,Ohio,15,4
Darke County,Ohio,12,4
Defiance County,Ohio,15,4
Delaware County,Ohio,15,4
Erie County,Ohio,11,4
Fairfield County,Ohio,16,4
Fayette County,Ohio,14,4
Franklin County,Ohio,15,4
Fulton County,Ohio,13,4
Gallia County,Ohio,13,4
Geauga County,Ohio,13,4
Greene County,Ohio,13,4
Guernsey County,Ohio,15,4
Hamilton County,Ohio,15,4
Hancock County,Ohio,14,4
Hardin County,Ohio,13,4
Harrison County,Ohio,15,4
Henry County,Ohio,12,4
Highland County,Ohio,15,4
Hocking County,Ohio,14,4
Holmes County,Ohio,13,4
Huron County,Ohio,12,4
Jackson County,Ohio,14,4
Jefferson County,Ohio,16,4
Knox County,Ohio,11,4
Lake County,Ohio,11,4
Lawrence County,Ohio,15,4
Licking County,Ohio,14,4
Logan County,Ohio,12,4
Lorain County,Ohio,13,4
Lucas County,Ohio,12,4
Madison County,Ohio,14,4
Mahoning County,Ohio,15,4
Marion County,Ohio,13,4
Medina County,Ohio,13,4
Meigs County,Ohio,12,4
Mercer County,Ohio,13,4
Miami County,Ohio,12,4
Monroe County,Ohio,13,4
Montgomery County,Ohio,17,4
Morgan County,Ohio,13,4
Morrow County,Ohio,13,4
Muskingum County,Ohio,16,4
Noble County,Ohio,12,4
Ottawa County,Ohio,13,4
Paulding County,Ohio,15,4
Perry County,Ohio,12,4
Pickaway County,Ohio,15,4
Pike County,Ohio,11,4
Portage County,Ohio,14,4
Preble County,Ohio,13,4
Putnam County,Ohio,13,4
Richland County,Ohio,15,4
Ross County,Ohio,11,4
Sandusky County,Ohio,15,4
Scioto County,Ohio,13,4
Seneca County,Ohio,13,4
Shelby County,Ohio,13,4
Stark County,Ohio,12,4
Summit County,Ohio,13,4
Trumbull County,Ohio,15,4
Tuscarawas County,Ohio,17,4
Union County,Ohio,12,4
Van Wert County,Ohio,15,4
Vinton County,Ohio,13,4
Warren County,Ohio,13,4
Washington County,Ohio,17,4
Wayne County,Ohio,12,4
Williams County,Ohio,15,4
Wood County,Ohio,11,4
Wyandot County,Ohio,14,4
Adair County,Oklahoma,12,8
Alfalfa County,Oklahoma,14,8
Atoka County,Oklahoma,12,8
Beaver County,Oklahoma,13,8
Beckham County,Oklahoma,14,8
Blaine County,Oklahoma,13,8
Bryan County,Oklahoma,12,8
Caddo County,Oklahoma,12,8
Canadian County,Oklahoma,15,8
Carter County,Oklahoma,13,8
Cherokee County,Oklahoma,15,8
Choctaw County,Oklahoma,14,8
Cimarron County,Oklahoma,15,8
Cleveland County,Oklahoma,16,8
Coal County,Oklahoma,11,8
Comanche County,Oklahoma,15,8
Cotton County,Oklahoma,13,8
Craig County,Oklahoma,12,8
Creek County,Oklahoma,12,8
Custer County,Oklahoma,13,8
Delaware County,Oklahoma,15,8
Dewey County,Oklahoma,12,8
Ellis County,Oklahoma,12,8
Garfield County,Oklahoma,15,8
Garvin County,Oklahoma,13,8
Grady County,Oklahoma,12,8
Grant County,Oklahoma,12,8
Greer County,Oklahoma,12,8
Harmon County,Oklahoma,13,8
Harper County,Oklahoma,13,8
Haskell County,Oklahoma,14,8
Hughes County,Oklahoma,13,8
Jackson County,Oklahoma,14,8
Jefferson County,Oklahoma,16,8
Johnston County,Oklahoma,15,8
Kay County,Oklahoma,10,8
Kingfisher County,Oklahoma,17,8
Kiowa County,Oklahoma,12,8
Latimer County,Oklahoma,14,8
Le Flore County,Oklahoma,15,8
Lincoln County,Oklahoma,14,8
Logan County,Oklahoma,12,8
Love County,Oklahoma,11,8
Major County,Oklahoma,12,8
Marshall County,Oklahoma,15,8
Mayes County,Oklahoma,12,8
McClain County,Oklahoma,14,8
McCurtain County,Oklahoma,16,8
McIntosh County,Oklahoma,15,8
Murray County,Oklahoma,13,8
Muskogee County,Oklahoma,15,8
Noble County,Oklahoma,12,8
Nowata County,Oklahoma,13,8
Okfuskee County,Oklahoma,15,8
Oklahoma County,Oklahoma,15,8
Okmulgee County,Oklahoma,15,8
Osage County,Oklahoma,12,8
Ottawa County,Oklahoma,13,8
Pawnee County,Oklahoma,13,8
Payne County,Oklahoma,12,8
Pittsburg County,Oklahoma,16,8
Pontotoc County,Oklahoma,15,8
Pottawatomie County,Oklahoma,19,8
Pushmataha County,Oklahoma,17,8
Roger Mills County,Oklahoma,18,8
Rogers County,Oklahoma,13,8
Seminole County,Oklahoma,15,8
Sequoyah County,Oklahoma,15,8
Stephens County,Oklahoma,15,8
Texas County,Oklahoma,12,8
Tillman County,Oklahoma,14,8
Tulsa County,Oklahoma,12,8
Wagoner County,Oklahoma,14,8
Washington County,Oklahoma,17,8
Washita County,Oklahoma,14,8
Woods County,Oklahoma,12,8
Woodward County,Oklahoma,15,8
Baker County,Oregon,12,6
Benton County,Oregon,13,6
Clackamas County,Oregon,16,6
Clatsop County,Oregon,14,6
Columbia County,Oregon,15,6
Coos County,Oregon,11,6
Crook County,Oregon,12,6
Curry County,Oregon,12,6
Deschutes County,Oregon,16,6
Douglas County,Oregon,14,6
Gilliam County,Oregon,14,6
Grant County,Oregon,12,6
Harney County,Oregon,13,6
Hood River County,Oregon,17,6
Jackson County,Oregon,14,6
Jefferson County,Oregon,16,6
Josephine County,Oregon,16,6
Klamath County,Oregon,14,6
Lake County,Oregon,11,6
Lane County,Oregon,11,6
Lincoln County,Oregon,14,6
Linn County,Oregon,11,6
Malheur County,Oregon,14,6
Marion County,Oregon,13,6
Morrow County,Oregon,13,6
Multnomah County,Oregon,16,6
Polk County,Oregon,11,6
Sherman County,Oregon,14,6
Tillamook County,Oregon,16,6
Umatilla County,Oregon,15,6
Union County,Oregon,12,6
Wallowa County,Oregon,14,6
Wasco County,Oregon,12,6
Washington County,Oregon,17,6
Wheeler County,Oregon,14,6
Yamhill County,Oregon,14,6
Adams County,Pennsylvania,12,12
Allegheny County,Pennsylvania,16,12
Armstrong County,Pennsylvania,16,12
Beaver County,Pennsylvania,13,12
Bedford County,Pennsylvania,14,12
Berks County,Pennsylvania,12,12
Blair County,Pennsylvania,12,12
Bradford County,Pennsylvania,15,12
Bucks County,Pennsylvania,12,12
Butler County,Pennsylvania,13,12
Cambria County,Pennsylvania,14,12
Cameron County,Pennsylvania,14,12
Carbon County,Pennsylvania,13,12
Centre County,Pennsylvania,13,12
Chester County,Pennsylvania,14,12
Clarion County,Pennsylvania,14,12
Clearfield County,Pennsylvania,17,12
Clinton County,Pennsylvania,14,12
Columbia County,Pennsylvania,15,12
Crawford County,Pennsylvania,15,12
Cumberland County,Pennsylvania,17,12
Dauphin County,Pennsylvania,14,12
Delaware County,Pennsylvania,15,12
Elk County,Pennsylvania,10,12
Erie County,Pennsylvania,11,12
Fayette County,Pennsylvania,14,12
Forest County,Pennsylvania,13,12
Franklin County,Pennsylvania,15,12
Fulton County,Pennsylvania,13,12
Greene County,Pennsylvania,13,12
Huntingdon County,Pennsylvania,17,12
Indiana County,Pennsylvania,14,12
Jefferson County,Pennsylvania,16,12
Juniata County,Pennsylvania,14,12
Lackawanna County,Pennsylvania,17,12
Lancaster County,Pennsylvania,16,12
Lawrence County,Pennsylvania,15,12
Lebanon County,Pennsylvania,14,12
Lehigh County,Pennsylvania,13,12
Luzerne County,Pennsylvania,14,12
Lycoming County,Pennsylvania,15,12
McKean County,Pennsylvania,13,12
Mercer County,Pennsylvania,13,12
Mifflin County,Pennsylvania,14,12
Monroe County,Pennsylvania,13,12
Montgomery County,Pennsylvania,17,12
Montour County,Pennsylvania,14,12
Northampton County,Pennsylvania,18,12
Northumberland County,Pennsylvania,21,12
Perry County,Pennsylvania,12,12
Philadelphia County,Pennsylvania,19,12
Pike County,Pennsylvania,11,12
Potter County,Pennsylvania,13,12
Schuylkill County,Pennsylvania,17,12
Snyder County,Pennsylvania,13,12
Somerset County,Pennsylvania,15,12
Sullivan County,Pennsylvania,15,12
Susquehanna County,Pennsylvania,18,12
Tioga County,Pennsylvania,12,12
Union County,Pennsylvania,12,12
Venango County,Pennsylvania,14,12
Warren County,Pennsylvania,13,12
Washington County,Pennsylvania,17,12
Wayne County,Pennsylvania,12,12
Westmoreland County,Pennsylvania,19,12
Wyoming County,Pennsylvania,14,12
York County,Pennsylvania,11,12
Bristol County,Rhode Island,14,12
Kent County,Rhode Island,11,12
Newport County,Rhode Island,14,12
Providence County,Rhode Island,17,12
Washington County,Rhode Island,17,12
Abbeville County,South Carolina,16,14
Aiken County,South Carolina,12,14
Allendale County,South Carolina,16,14
Anderson County,South Carolina,15,14
Bamberg County,South Carolina,14,14
Barnwell County,South Carolina,15,14
Beaufort County,South Carolina,15,14
Berkeley County,South Carolina,15,14
Calhoun County,South Carolina,14,14
Charleston County,South Carolina,17,14
Cherokee County,South Carolina,15,14
Chester County,South Carolina,14,14
Chesterfield County,South Carolina,19,14
Clarendon County,South Carolina,16,14
Colleton County,South Carolina,15,14
Darlington County,South Carolina,17,14
Dillon County,South Carolina,13,14
Dorchester County,South Carolina,17,14
Edgefield County,South Carolina,16,14
Fairfield County,South Carolina,16,14
Florence County,South Carolina,15,14
Georgetown County,South Carolina,17,14
Greenville County,South Carolina,17,14
Greenwood County,South Carolina,16,14
Hampton County,South Carolina,14,14
Horry County,South Carolina,12,14
Jasper County,South Carolina,13,14
Kershaw County,South Carolina,14,14
Lancaster County,South Carolina,16,14
Laurens County,South Carolina,14,14
Lee County,South Carolina,10,14
Lexington County,South Carolina,16,14
Marion County,South Carolina,13,14
Marlboro County,South Carolina,15,14
McCormick County,South Carolina,16,14
Newberry County,South Carolina,15,14
Oconee County,South Carolina,13,14
Orangeburg County,South Carolina,17,14
Pickens County,South Carolina,14,14
Richland County,South Carolina,15,14
Saluda County,South Carolina,13,14
Spartanburg County,South Carolina,18,14
Sumter County,South Carolina,13,14
Union County,South Carolina,12,14
Williamsburg County,South Carolina,19,14
York County,South Carolina,11,14
Aurora County,South Dakota,13,12
Beadle County,South Dakota,13,12
Bennett County,South Dakota,14,12
Bon Homme County,South Dakota,16,12
Brookings County,South Dakota,16,12
Brown County,South Dakota,12,12
Brule County,South Dakota,12,12
Buffalo County,South Dakota,14,12
Butte County,South Dakota,12,12
Campbell County,South Dakota,15,12
Charles Mix County,South Dakota,18,12
Clark County,South Dakota,12,12
Clay County,South Dakota,11,12
Codington County,South Dakota,16,12
Corson County,South Dakota,13,12
Custer County,South Dakota,13,12
Davison County,South Dakota,14,12
Day County,South Dakota,10,12
Deuel County,South Dakota,12,12
Dewey County,South Dakota,12,12
Douglas County,South Dakota,14,12
Edmunds County,South Dakota,14,12
Fall River County,South Dakota,17,12
Faulk County,South Dakota,12,12
Grant County,South Dakota,12,12
Gregory County,South Dakota,14,12
Haakon County,South Dakota,13,12
Hamlin County,South Dakota,13,12
Hand County,South Dakota,11,12
Hanson County,South Dakota,13,12
Harding County,South Dakota,14,12
Hughes County,South Dakota,13,12
Hutchinson County,South Dakota,17,12
Hyde County,South Dakota,11,12
Jackson County,South Dakota,14,12
Jerauld County,South Dakota,14,12
Jones County,South Dakota,12,12
Kingsbury County,South Dakota,16,12
Lake County,South Dakota,11,12
Lawrence County,South Dakota,15,12
Lincoln County,South Dakota,14,12
Lyman County,South Dakota,12,12
Marshall County,South Dakota,15,12
McCook County,South Dakota,13,12
McPherson County,South Dakota,16,12
Meade County,South Dakota,12,12
Mellette County,South Dakota,15,12
Miner County,South Dakota,12,12
Minnehaha County,South Dakota,16,12
Moody County,South Dakota,12,12
Pennington County,South Dakota,17,12
Perkins County,South Dakota,14,12
Potter County,South Dakota,13,12
Roberts County,South Dakota,14,12
Sanborn County,South Dakota,14,12
Shannon County,South Dakota,14,12
Spink County,South Dakota,12,12
Stanley County,South Dakota,14,12
Sully County,South Dakota,12,12
Todd County,South Dakota,11,12
Tripp County,South Dakota,12,12
Turner County,South Dakota,13,12
Union County,South Dakota,12,12
Walworth County,South Dakota,15,12
Yankton County,South Dakota,14,12
Ziebach County,South Dakota,14,12
Anderson County,Tennessee,15,9
Bedford County,Tennessee,14,9
Benton County,Tennessee,13,9
Bledsoe County,Tennessee,14,9
Blount County,Tennessee,13,9
Bradley County,Tennessee,14,9
Campbell County,Tennessee,15,9
Cannon County,Tennessee,13,9
Carroll County,Tennessee,14,9
Carter County,Tennessee,13,9
Cheatham County,Tennessee,15,9
Chester County,Tennessee,14,9
Claiborne County,Tennessee,16,9
Clay County,Tennessee,11,9
Cocke County,Tennessee,12,9
Coffee County,Tennessee,13,9
Crockett County,Tennessee,15,9
Cumberland County,Tennessee,17,9
Davidson County,Tennessee,15,9
DeKalb County,Tennessee,13,9
Decatur County,Tennessee,14,9
Dickson County,Tennessee,14,9
Dyer County,Tennessee,11,9
Fayette County,Tennessee,14,9
Fentress County,Tennessee,15,9
Franklin County,Tennessee,15,9
Gibson County,Tennessee,13,9
Giles County,Tennessee,12,9
Grainger County,Tennessee,15,9
Greene County,Tennessee,13,9
Grundy County,Tennessee,13,9
Hamblen County,Tennessee,14,9
Hamilton County,Tennessee,15,9
Hancock County,Tennessee,14,9
Hardeman County,Tennessee,15,9
Hardin County,Tennessee,13,9
Hawkins County,Tennessee,14,9
Haywood County,Tennessee,14,9
Henderson County,Tennessee,16,9
Henry County,Tennessee,12,9
Hickman County,Tennessee,14,9
Houston County,Tennessee,14,9
Humphreys County,Tennessee,16,9
Jackson County,Tennessee,14,9
Jefferson County,Tennessee,16,9
Johnson County,Tennessee,14,9
Knox County,Tennessee,11,9
Lake County,Tennessee,11,9
Lauderdale County,Tennessee,17,9
Lawrence County,Tennessee,15,9
Lewis County,Tennessee,12,9
Lincoln County,Tennessee,14,9
Loudon County,Tennessee,13,9
Macon County,Tennessee,12,9
Madison County,Tennessee,14,9
Marion County,Tennessee,13,9
Marshall County,Tennessee,15,9
Maury County,Tennessee,12,9
McMinn County,Tennessee,13,9
McNairy County,Tennessee,14,9
Meigs County,Tennessee,12,9
Monroe County,Tennessee,13,9
Montgomery County,Tennessee,17,9
Moore County,Tennessee,12,9
Morgan County,Tennessee,13,9
Obion County,Tennessee,12,9
Overton County,Tennessee,14,9
Perry County,Tennessee,12,9
Pickett County,Tennessee,14,9
Polk County,Tennessee,11,9
Putnam County,Tennessee,13,9
Rhea County,Tennessee,11,9
Roane County,Tennessee,12,9
Robertson County,Tennessee,16,9
Rutherford County,Tennessee,17,9
Scott County,Tennessee,12,9
Sequatchie County,Tennessee,17,9
Sevier County,Tennessee,13,9
Shelby County,Tennessee,13,9
Smith County,Tennessee,12,9
Stewart County,Tennessee,14,9
Sullivan County,Tennessee,15,9
Sumner County,Tennessee,13,9
Tipton County,Tennessee,13,9
Trousdale County,Tennessee,16,9
Unicoi County,Tennessee,13,9
Union County,Tennessee,12,9
Van Buren County,Tennessee,16,9
Warren County,Tennessee,13,9
Washington County,Tennessee,17,9
Wayne County,Tennessee,12,9
Weakley County,Tennessee,14,9
White County,Tennessee,12,9
Williamson County,Tennessee,17,9
Wilson County,Tennessee,13,9
Anderson County,Texas,15,5
Andrews County,Texas,14,5
Angelina County,Texas,15,5
Aransas County,Texas,14,5
Archer County,Texas,13,5
Armstrong County,Texas,16,5
Atascosa County,Texas,15,5
Austin County,Texas,13,5
Bailey County,Texas,13,5
Bandera County,Texas,14,5
Bastrop County,Texas,14,5
Baylor County,Texas,13,5
Bee County,Texas,10,5
Bell County,Texas,11,5
Bexar County,Texas,12,5
Blanco County,Texas,13,5
Borden County,Texas,13,5
Bosque County,Texas,13,5
Bowie County,Texas,12,5
Brazoria County,Texas,15,5
Brazos County,Texas,13,5
Brewster County,Texas,15,5
Briscoe County,Texas,14,5
Brooks County,Texas,13,5
Brown County,Texas,12,5
Burleson County,Texas,15,5
Burnet County,Texas,13,5
Caldwell County,Texas,15,5
Calhoun County,Texas,14,5
Callahan County,Texas,15,5
Cameron County,Texas,14,5
Camp County,Texas,11,5
Carson County,Texas,13,5
Cass County,Texas,11,5
Castro County,Texas,13,5
Chambers County,Texas,15,5
Cherokee County,Texas,15,5
Childress County,Texas,16,5
Clay County,Texas,11,5
Cochran County,Texas,14,5
Coke County,Texas,11,5
Coleman County,Texas,14,5
Collin County,Texas,13,5
Collingsworth County,Texas,20,5
Colorado County,Texas,15,5
Comal County,Texas,12,5
Comanche County,Texas,15,5
Concho County,Texas,13,5
Cooke County,Texas,12,5
Coryell County,Texas,14,5
Cottle County,Texas,13,5
Crane County,Texas,12,5
Crockett County,Texas,15,5
Crosby County,Texas,13,5
Culberson County,Texas,16,5
Dallam County,Texas,13,5
Dallas County,Texas,13,5
Dawson County,Texas,13,5
DeWitt County,Texas,13,5
Deaf Smith County,Texas,17,5
Delta County,Texas,12,5
Denton County,Texas,13,5
Dickens County,Texas,14,5
Dimmit County,Texas,13,5
Donley County,Texas,13,5
Duval County,Texas,12,5
Eastland County,Texas,15,5
Ector County,Texas,12,5
Edwards County,Texas,14,5
El Paso County,Texas,14,5
Ellis County,Texas,12,5
Erath County,Texas,12,5
Falls County,Texas,12,5
Fannin County,Texas,13,5
Fayette County,Texas,14,5
Fisher County,Texas,13,5
Floyd County,Texas,12,5
Foard County,Texas,12,5
Fort Bend County,Texas,16,5
Franklin County,Texas,15,5
Freestone County,Texas,16,5
Frio County,Texas,11,5
Gaines County,Texas,13,5
Galveston County,Texas,16,5
Garza County,Texas,12,5
Gillespie County,Texas,16,5
Glasscock County,Texas,16,5
Goliad County,Texas,13,5
Gonzales County,Texas,15,5
Gray County,Texas,11,5
Grayson County,Texas,14,5
Gregg County,Texas,12,5
Grimes County,Texas,13,5
Guadalupe County,Texas,16,5
Hale County,Texas,11,5
Hall County,Texas,11,5
Hamilton County,Texas,15,5
Hansford County,Texas,15,5
Hardeman County,Texas,15,5
Hardin County,Texas,13,5
Harris County,Texas,13,5
Harrison County,Texas,15,5
Hartley County,Texas,14,5
Haskell County,Texas,14,5
Hays County,Texas,11,5
Hemphill County,Texas,15,5
Henderson County,Texas,16,5
Hidalgo County,Texas,14,5
Hill County,Texas,11,5
Hockley County,Texas,14,5
Hood County,Texas,11,5
Hopkins County,Texas,14,5
Houston County,Texas,14,5
Howard County,Texas,13,5
Hudspeth County,Texas,15,5
Hunt County,Texas,11,5
Hutchinson County,Texas,17,5
Irion County,Texas,12,5
Jack County,Texas,11,5
Jackson County,Texas,14,5
Jasper County,Texas,13,5
Jeff Davis County,Texas,17,5
Jefferson County,Texas,16,5
Jim Hogg County,Texas,15,5
Jim Wells County,Texas,16,5
Johnson County,Texas,14,5
Jones County,Texas,12,5
Karnes County,Texas,13,5
Kaufman County,Texas,14,5
Kendall County,Texas,14,5
Kenedy County,Texas,13,5
Kent County,Texas,11,5
Kerr County,Texas,11,5
Kimble County,Texas,13,5
King County,Texas,11,5
Kinney County,Texas,13,5
Kleberg County,Texas,14,5
Knox County,Texas,11,5
La Salle County,Texas,15,5
Lamar County,Texas,12,5
Lamb County,Texas,11,5
Lampasas County,Texas,15,5
Lavaca County,Texas,13,5
Lee County,Texas,10,5
Leon County,Texas,11,5
Liberty County,Texas,14,5
Limestone County,Texas,16,5
Lipscomb County,Texas,15,5
Live Oak County,Texas,15,5
Llano County,Texas,12,5
Loving County,Texas,13,5
Lubbock County,Texas,14,5
Lynn County,Texas,11,5
Madison County,Texas,14,5
Marion County,Texas,13,5
Martin County,Texas,13,5
Mason County,Texas,12,5
Matagorda County,Texas,16,5
Maverick County,Texas,15,5
McCulloch County,Texas,16,5
McLennan County,Texas,15,5
McMullen County,Texas,15,5
Medina County,Texas,13,5
Menard County,Texas,13,5
Midland County,Texas,14,5
Milam County,Texas,12,5
Mills County,Texas,12,5
Mitchell County,Texas,15,5
Montague County,Texas,15,5
Montgomery County,Texas,17,5
Moore County,Texas,12,5
Morris County,Texas,13,5
Motley County,Texas,13,5
Nacogdoches County,Texas,18,5
Navarro County,Texas,14,5
Newton County,Texas,13,5
Nolan County,Texas,12,5
Nueces County,Texas,13,5
Ochiltree County,Texas,16,5
Oldham County,Texas,13,5
Orange County,Texas,13,5
Palo Pinto County,Texas,17,5
Panola County,Texas,13,5
Parker County,Texas,13,5
Parmer County,Texas,13,5
Pecos County,Texas,12,5
Polk County,Texas,11,5
Potter County,Texas,13,5
Presidio County,Texas,15,5
Rains County,Texas,12,5
Randall County,Texas,14,5
Reagan County,Texas,13,5
Real County,Texas,11,5
Red River County,Texas,16,5
Reeves County,Texas,13,5
Refugio County,Texas,14,5
Roberts County,Texas,14,5
Robertson County,Texas,16,5
Rockwall County,Texas,15,5
Runnels County,Texas,14,5
Rusk County,Texas,11,5
Sabine County,Texas,13,5
San Augustine County,Texas,20,5
San Jacinto County,Texas,18,5
San Patricio County,Texas,19,5
San Saba County,Texas,15,5
Schleicher County,Texas,17,5
Scurry County,Texas,13,5
Shackelford County,Texas,18,5
Shelby County,Texas,13,5
Sherman County,Texas,14,5
Smith County,Texas,12,5
Somervell County,Texas,16,5
Starr County,Texas,12,5
Stephens County,Texas,15,5
Sterling County,Texas,15,5
Stonewall County,Texas,16,5
Sutton County,Texas,13,5
Swisher County,Texas,14,5
Tarrant County,Texas,14,5
Taylor County,Texas,13,5
Terrell County,Texas,14,5
Terry County,Texas,12,5
Throckmorton County,Texas,19,5
Titus County,Texas,12,5
Tom Green County,Texas,16,5
Travis County,Texas,13,5
Trinity County,Texas,14,5
Tyler County,Texas,12,5
Upshur County,Texas,13,5
Upton County,Texas,12,5
Uvalde County,Texas,13,5
Val Verde County,Texas,16,5
Van Zandt County,Texas,16,5
Victoria County,Texas,15,5
Walker County,Texas,13,5
Waller County,Texas,13,5
Ward County,Texas,11,5
Washington County,Texas,17,5
Webb County,Texas,11,5
Wharton County,Texas,14,5
Wheeler County,Texas,14,5
Wichita County,Texas,14,5
Wilbarger County,Texas,16,5
Willacy County,Texas,14,5
Williamson County,Texas,17,5
Wilson County,Texas,13,5
Winkler County,Texas,14,5
Wise County,Texas,11,5
Wood County,Texas,11,5
Yoakum County,Texas,13,5
Young County,Texas,12,5
Zapata County,Texas,13,5
Zavala County,Texas,13,5
Beaver County,Utah,13,4
Box Elder County,Utah,16,4
Cache County,Utah,12,4
Carbon County,Utah,13,4
Daggett County,Utah,14,4
Davis County,Utah,12,4
Duchesne County,Utah,15,4
Emery County,Utah,12,4
Garfield County,Utah,15,4
Grand County,Utah,12,4
Iron County,Utah,11,4
Juab County,Utah,11,4
Kane County,Utah,11,4
Millard County,Utah,14,4
Morgan County,Utah,13,4
Piute County,Utah,12,4
Rich County,Utah,11,4
Salt Lake County,Utah,16,4
San Juan County,Utah,15,4
Sanpete County,Utah,14,4
Sevier County,Utah,13,4
Summit County,Utah,13,4
Tooele County,Utah,13,4
Uintah County,Utah,13,4
Utah County,Utah,11,4
Wasatch County,Utah,14,4
Washington County,Utah,17,4
Wayne County,Utah,12,4
Weber County,Utah,12,4
Addison County,Vermont,14,7
Bennington County,Vermont,17,7
Caledonia County,Vermont,16,7
Chittenden County,Vermont,17,7
Essex County,Vermont,12,7
Franklin County,Vermont,15,7
Grand Isle County,Vermont,17,7
Lamoille County,Vermont,15,7
Orange County,Vermont,13,7
Orleans County,Vermont,14,7
Rutland County,Vermont,14,7
Washington County,Vermont,17,7
Windham County,Vermont,14,7
Windsor County,Vermont,14,7
Accomack County,Virginia,15,8
Albemarle County,Virginia,16,8
Alleghany County,Virginia,16,8
Amelia County,Virginia,13,8
Amherst County,Virginia,14,8
Appomattox County,Virginia,17,8
Arlington County,Virginia,16,8
Augusta County,Virginia,14,8
Bath County,Virginia,11,8
Bedford County,Virginia,14,8
Bland County,Virginia,12,8
Botetourt County,Virginia,16,8
Brunswick County,Virginia,16,8
Buchanan County,Virginia,15,8
Buckingham County,Virginia,17,8
Campbell County,Virginia,15,8
Caroline County,Virginia,15,8
Carroll County,Virginia,14,8
Charles City County,Virginia,19,8
Charlotte County,Virginia,16,8
Chesterfield County,Virginia,19,8
Clarke County,Virginia,13,8
Craig County,Virginia,12,8
Culpeper County,Virginia,15,8
Cumberland County,Virginia,17,8
Dickenson County,Virginia,16,8
Dinwiddie County,Virginia,16,8
Essex County,Virginia,12,8
Fairfax County,Virginia,14,8
Fauquier County,Virginia,15,8
Floyd County,Virginia,12,8
Fluvanna County,Virginia,15,8
Franklin County,Virginia,15,8
Frederick County,Virginia,16,8
Giles County,Virginia,12,8
Gloucester County,Virginia,17,8
Goochland County,Virginia,16,8
Grayson County,Virginia,14,8
Greene County,Virginia,13,8
Greensville County,Virginia,18,8
Halifax County,Virginia,14,8
Hanover County,Virginia,14,8
Henrico County,Virginia,14,8
Henry County,Virginia,12,8
Highland County,Virginia,15,8
Isle of Wight County,Virginia,20,8
James City County,Virginia,17,8
King George County,Virginia,18,8
King William County,Virginia,19,8
King and Queen County,Virginia,21,8
Lancaster County,Virginia,16,8
Lee County,Virginia,10,8
Loudoun County,Virginia,14,8
Louisa County,Virginia,13,8
Lunenburg County,Virginia,16,8
Madison County,Virginia,14,8
Mathews County,Virginia,14,8
Mecklenburg County,Virginia,18,8
Middlesex County,Virginia,16,8
Montgomery County,Virginia,17,8
Nelson County,Virginia,13,8
New Kent County,Virginia,15,8
Northampton County,Virginia,18,8
Northumberland County,Virginia,21,8
Nottoway County,Virginia,15,8
Orange County,Virginia,13,8
Page County,Virginia,11,8
Patrick County,Virginia,14,8
Pittsylvania County,Virginia,19,8
Powhatan County,Virginia,15,8
Prince Edward County,Virginia,20,8
Prince George County,Virginia,20,8
Prince William County,Virginia,21,8
Pulaski County,Virginia,14,8
Rappahannock County,Virginia,19,8
Richmond County,Virginia,15,8
Roanoke County,Virginia,14,8
Rockbridge County,Virginia,17,8
Rockingham County,Virginia,17,8
Russell County,Virginia,14,8
Scott County,Virginia,12,8
Shenandoah County,Virginia,17,8
Smyth County,Virginia,12,8
Southampton County,Virginia,18,8
Spotsylvania County,Virginia,19,8
Stafford County,Virginia,15,8
Surry County,Virginia,12,8
Sussex County,Virginia,13,8
Tazewell County,Virginia,15,8
Warren County,Virginia,13,8
Washington County,Virginia,17,8
Westmoreland County,Virginia,19,8
Wise County,Virginia,11,8
Wythe County,Virginia,12,8
York County,Virginia,11,8
Adams County,Washington,12,10
Asotin County,Washington,13,10
Benton County,Washington,13,10
Chelan County,Washington,13,10
Clallam County,Washington,14,10
Clark County,Washington,12,10
Columbia County,Washington,15,10
Cowlitz County,Washington,14,10
Douglas County,Washington,14,10
Ferry County,Washington,12,10
Franklin County,Washington,15,10
Garfield County,Washington,15,10
Grant County,Washington,12,10
Grays Harbor County,Washington,19,10
Island County,Washington,13,10
Jefferson County,Washington,16,10
King County,Washington,11,10
Kitsap County,Washington,13,10
Kittitas County,Washington,15,10
Klickitat County,Washington,16,10
Lewis County,Washington,12,10
Lincoln County,Washington,14,10
Mason County,Washington,12,10
Okanogan County,Washington,15,10
Pacific County,Washington,14,10
Pend Oreille County,Washington,19,10
Pierce County,Washington,13,10
San Juan County,Washington,15,10
Skagit County,Washington,13,10
Skamania County,Washington,15,10
Snohomish County,Washington,16,10
Spokane County,Washington,14,10
Stevens County,Washington,14,10
Thurston County,Washington,15,10
Wahkiakum County,Washington,16,10
Walla Walla County,Washington,18,10
Whatcom County,Washington,14,10
Whitman County,Washington,14,10
Yakima County,Washington,13,10
Barbour County,West Virginia,14,13
Berkeley County,West Virginia,15,13
Boone County,West Virginia,12,13
Braxton County,West Virginia,14,13
Brooke County,West Virginia,13,13
Cabell County,West Virginia,13,13
Calhoun County,West Virginia,14,13
Clay County,West Virginia,11,13
Doddridge County,West Virginia,16,13
Fayette County,West Virginia,14,13
Gilmer County,West Virginia,13,13
Grant County,West Virginia,12,13
Greenbrier County,West Virginia,17,13
Hampshire County,West Virginia,16,13
Hancock County,West Virginia,14,13
Hardy County,West Virginia,12,13
Harrison County,West Virginia,15,13
Jackson County,West Virginia,14,13
Jefferson County,West Virginia,16,13
Kanawha County,West Virginia,14,13
Lewis County,West Virginia,12,13
Lincoln County,West Virginia,14,13
Logan County,West Virginia,12,13
Marion County,West Virginia,13,13
Marshall County,West Virginia,15,13
Mason County,West Virginia,12,13
McDowell County,West Virginia,15,13
Mercer County,West Virginia,13,13
Mineral County,West Virginia,14,13
Mingo County,West Virginia,12,13
Monongalia County,West Virginia,17,13
Monroe County,West Virginia,13,13
Morgan County,West Virginia,13,13
Nicholas County,West Virginia,15,13
Ohio County,West Virginia,11,13
Pendleton County,West Virginia,16,13
Pleasants County,West Virginia,16,13
Pocahontas County,West Virginia,17,13
Preston County,West Virginia,14,13
Putnam County,West Virginia,13,13
Raleigh County,West Virginia,14,13
Randolph County,West Virginia,15,13
Ritchie County,West Virginia,14,13
Roane County,West Virginia,12,13
Summers County,West Virginia,14,13
Taylor County,West Virginia,13,13
Tucker County,West Virginia,13,13
Tyler County,West Virginia,12,13
Upshur County,West Virginia,13,13
Wayne County,West Virginia,12,13
Webster County,West Virginia,14,13
Wetzel County,West Virginia,13,13
Wirt County,West Virginia,11,13
Wood County,West Virginia,11,13
Wyoming County,West Virginia,14,13
Adams County,Wisconsin,12,9
Ashland County,Wisconsin,14,9
Barron County,Wisconsin,13,9
Bayfield County,Wisconsin,15,9
Brown County,Wisconsin,12,9
Buffalo County,Wisconsin,14,9
Burnett County,Wisconsin,14,9
Calumet County,Wisconsin,14,9
Chippewa County,Wisconsin,15,9
Clark County,Wisconsin,12,9
Columbia County,Wisconsin,15,9
Crawford County,Wisconsin,15,9
Dane County,Wisconsin,11,9
Dodge County,Wisconsin,12,9
Door County,Wisconsin,11,9
Douglas County,Wisconsin,14,9
Dunn County,Wisconsin,11,9
Eau Claire County,Wisconsin,17,9
Florence County,Wisconsin,15,9
Fond du Lac County,Wisconsin,18,9
Forest County,Wisconsin,13,9
Grant County,Wisconsin,12,9
Green County,Wisconsin,12,9
Green Lake County,Wisconsin,17,9
Iowa County,Wisconsin,11,9
Iron County,Wisconsin,11,9
Jackson County,Wisconsin,14,9
Jefferson County,Wisconsin,16,9
Juneau County,Wisconsin,13,9
Kenosha County,Wisconsin,14,9
Kewaunee County,Wisconsin,15,9
La Crosse County,Wisconsin,16,9
Lafayette County,Wisconsin,16,9
Langlade County,Wisconsin,15,9
Lincoln County,Wisconsin,14,9
Manitowoc County,Wisconsin,16,9
Marathon County,Wisconsin,15,9
Marinette County,Wisconsin,16,9
Marquette County,Wisconsin,16,9
Menominee County,Wisconsin,16,9
Milwaukee County,Wisconsin,16,9
Monroe County,Wisconsin,13,9
Oconto County,Wisconsin,13,9
Oneida County,Wisconsin,13,9
Outagamie County,Wisconsin,16,9
Ozaukee County,Wisconsin,14,9
Pepin County,Wisconsin,12,9
Pierce County,Wisconsin,13,9
Polk County,Wisconsin,11,9
Portage County,Wisconsin,14,9
Price County,Wisconsin,12,9
Racine County,Wisconsin,13,9
Richland County,Wisconsin,15,9
Rock County,Wisconsin,11,9
Rusk County,Wisconsin,11,9
Sauk County,Wisconsin,11,9
Sawyer County,Wisconsin,13,9
Shawano County,Wisconsin,14,9
Sheboygan County,Wisconsin,16,9
St. Croix County,Wisconsin,16,9
Taylor County,Wisconsin,13,9
Trempealeau County,Wisconsin,18,9
Vernon County,Wisconsin,13,9
Vilas County,Wisconsin,12,9
Walworth County,Wisconsin,15,9
Washburn County,Wisconsin,15,9
Washington County,Wisconsin,17,9
Waukesha County,Wisconsin,15,9
Waupaca County,Wisconsin,14,9
Waushara County,Wisconsin,15,9
Winnebago County,Wisconsin,16,9
Wood County,Wisconsin,11,9
Albany County,Wyoming,13,7
Big Horn County,Wyoming,15,7
Campbell County,Wyoming,15,7
Carbon County,Wyoming,13,7
Converse County,Wyoming,15,7
Crook County,Wyoming,12,7
Fremont County,Wyoming,14,7
Goshen County,Wyoming,13,7
Hot Springs County,Wyoming,18,7
Johnson County,Wyoming,14,7
Laramie County,Wyoming,14,7
Lincoln County,Wyoming,14,7
Natrona County,Wyoming,14,7
Niobrara County,Wyoming,15,7
Park County,Wyoming,11,7
Platte County,Wyoming,13,7
Sheridan County,Wyoming,15,7
Sublette County,Wyoming,15,7
Sweetwater County,Wyoming,17,7
Teton County,Wyoming,12,7
Uinta County,Wyoming,12,7
Washakie County,Wyoming,15,7
Weston County,Wyoming,13,7
