name,state
Adams County,Washington
Asotin County,Washington
Benton County,Washington
Chelan County,Washington
Clallam County,Washington
Clark County,Washington
Columbia County,Washington
Cowlitz County,Washington
Douglas County,Washington
Ferry County,Washington
Franklin County,Washington
Garfield County,Washington
Grant County,Washington
Grays Harbor County,Washington
Island County,Washington
Jefferson County,Washington
King County,Washington
Kitsap County,Washington
Kittitas County,Washington
Klickitat County,Washington
Lewis County,Washington
Lincoln County,Washington
Mason County,Washington
Okanogan County,Washington
Pacific County,Washington
Pend Oreille County,Washington
Pierce County,Washington
San Juan County,Washington
Skagit County,Washington
Skamania County,Washington
Snohomish County,Washington
Spokane County,Washington
Stevens County,Washington
Thurston County,Washington
Wahkiakum County,Washington
Walla Walla County,Washington
Whatcom County,Washington
Whitman County,Washington
Yakima County,Washington
